// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.3
// source: booking.proto

package parking_lot

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ParkingBooking struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParkingLot    string                 `protobuf:"bytes,1,opt,name=parking_lot,json=parkingLot,proto3" json:"parking_lot,omitempty"`
	PhoneNumber   string                 `protobuf:"bytes,2,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	CarPlate      string                 `protobuf:"bytes,4,opt,name=car_plate,json=carPlate,proto3" json:"car_plate,omitempty"`
	TimeFrom      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=time_from,json=timeFrom,proto3" json:"time_from,omitempty"`
	TimeTo        *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=time_to,json=timeTo,proto3" json:"time_to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParkingBooking) Reset() {
	*x = ParkingBooking{}
	mi := &file_booking_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParkingBooking) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParkingBooking) ProtoMessage() {}

func (x *ParkingBooking) ProtoReflect() protoreflect.Message {
	mi := &file_booking_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParkingBooking.ProtoReflect.Descriptor instead.
func (*ParkingBooking) Descriptor() ([]byte, []int) {
	return file_booking_proto_rawDescGZIP(), []int{0}
}

func (x *ParkingBooking) GetParkingLot() string {
	if x != nil {
		return x.ParkingLot
	}
	return ""
}

func (x *ParkingBooking) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *ParkingBooking) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ParkingBooking) GetCarPlate() string {
	if x != nil {
		return x.CarPlate
	}
	return ""
}

func (x *ParkingBooking) GetTimeFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.TimeFrom
	}
	return nil
}

func (x *ParkingBooking) GetTimeTo() *timestamppb.Timestamp {
	if x != nil {
		return x.TimeTo
	}
	return nil
}

type AddParkingBookingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Booking       *ParkingBooking        `protobuf:"bytes,2,opt,name=booking,proto3" json:"booking,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddParkingBookingRequest) Reset() {
	*x = AddParkingBookingRequest{}
	mi := &file_booking_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddParkingBookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddParkingBookingRequest) ProtoMessage() {}

func (x *AddParkingBookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_booking_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddParkingBookingRequest.ProtoReflect.Descriptor instead.
func (*AddParkingBookingRequest) Descriptor() ([]byte, []int) {
	return file_booking_proto_rawDescGZIP(), []int{1}
}

func (x *AddParkingBookingRequest) GetBooking() *ParkingBooking {
	if x != nil {
		return x.Booking
	}
	return nil
}

type AddParkingBookingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParkingLot    string                 `protobuf:"bytes,1,opt,name=parking_lot,json=parkingLot,proto3" json:"parking_lot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddParkingBookingResponse) Reset() {
	*x = AddParkingBookingResponse{}
	mi := &file_booking_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddParkingBookingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddParkingBookingResponse) ProtoMessage() {}

func (x *AddParkingBookingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_booking_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddParkingBookingResponse.ProtoReflect.Descriptor instead.
func (*AddParkingBookingResponse) Descriptor() ([]byte, []int) {
	return file_booking_proto_rawDescGZIP(), []int{2}
}

func (x *AddParkingBookingResponse) GetParkingLot() string {
	if x != nil {
		return x.ParkingLot
	}
	return ""
}

type GetParkingBookingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParkingLot    string                 `protobuf:"bytes,1,opt,name=parking_lot,json=parkingLot,proto3" json:"parking_lot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetParkingBookingRequest) Reset() {
	*x = GetParkingBookingRequest{}
	mi := &file_booking_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetParkingBookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetParkingBookingRequest) ProtoMessage() {}

func (x *GetParkingBookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_booking_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetParkingBookingRequest.ProtoReflect.Descriptor instead.
func (*GetParkingBookingRequest) Descriptor() ([]byte, []int) {
	return file_booking_proto_rawDescGZIP(), []int{3}
}

func (x *GetParkingBookingRequest) GetParkingLot() string {
	if x != nil {
		return x.ParkingLot
	}
	return ""
}

type GetParkingBookingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Booking       *ParkingBooking        `protobuf:"bytes,1,opt,name=booking,proto3" json:"booking,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetParkingBookingResponse) Reset() {
	*x = GetParkingBookingResponse{}
	mi := &file_booking_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetParkingBookingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetParkingBookingResponse) ProtoMessage() {}

func (x *GetParkingBookingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_booking_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetParkingBookingResponse.ProtoReflect.Descriptor instead.
func (*GetParkingBookingResponse) Descriptor() ([]byte, []int) {
	return file_booking_proto_rawDescGZIP(), []int{4}
}

func (x *GetParkingBookingResponse) GetBooking() *ParkingBooking {
	if x != nil {
		return x.Booking
	}
	return nil
}

type GetParkingBookingsListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filter        string                 `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	Limit         int64                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`   // opt
	Offset        int64                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"` // opt
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetParkingBookingsListRequest) Reset() {
	*x = GetParkingBookingsListRequest{}
	mi := &file_booking_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetParkingBookingsListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetParkingBookingsListRequest) ProtoMessage() {}

func (x *GetParkingBookingsListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_booking_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetParkingBookingsListRequest.ProtoReflect.Descriptor instead.
func (*GetParkingBookingsListRequest) Descriptor() ([]byte, []int) {
	return file_booking_proto_rawDescGZIP(), []int{5}
}

func (x *GetParkingBookingsListRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

func (x *GetParkingBookingsListRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetParkingBookingsListRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetParkingBookingsListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bookings      []*ParkingBooking      `protobuf:"bytes,1,rep,name=bookings,proto3" json:"bookings,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetParkingBookingsListResponse) Reset() {
	*x = GetParkingBookingsListResponse{}
	mi := &file_booking_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetParkingBookingsListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetParkingBookingsListResponse) ProtoMessage() {}

func (x *GetParkingBookingsListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_booking_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetParkingBookingsListResponse.ProtoReflect.Descriptor instead.
func (*GetParkingBookingsListResponse) Descriptor() ([]byte, []int) {
	return file_booking_proto_rawDescGZIP(), []int{6}
}

func (x *GetParkingBookingsListResponse) GetBookings() []*ParkingBooking {
	if x != nil {
		return x.Bookings
	}
	return nil
}

func (x *GetParkingBookingsListResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_booking_proto protoreflect.FileDescriptor

const file_booking_proto_rawDesc = "" +
	"\n" +
	"\rbooking.proto\x12\x03api\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x87\x02\n" +
	"\x0eParkingBooking\x12\x1f\n" +
	"\vparking_lot\x18\x01 \x01(\tR\n" +
	"parkingLot\x12&\n" +
	"\fphone_number\x18\x02 \x01(\tB\x03\xe0A\x02R\vphoneNumber\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\tcar_plate\x18\x04 \x01(\tB\x03\xe0A\x02R\bcarPlate\x12<\n" +
	"\ttime_from\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x02R\btimeFrom\x128\n" +
	"\atime_to\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x02R\x06timeTo\"N\n" +
	"\x18AddParkingBookingRequest\x122\n" +
	"\abooking\x18\x02 \x01(\v2\x13.api.ParkingBookingB\x03\xe0A\x02R\abooking\"<\n" +
	"\x19AddParkingBookingResponse\x12\x1f\n" +
	"\vparking_lot\x18\x01 \x01(\tR\n" +
	"parkingLot\";\n" +
	"\x18GetParkingBookingRequest\x12\x1f\n" +
	"\vparking_lot\x18\x01 \x01(\tR\n" +
	"parkingLot\"J\n" +
	"\x19GetParkingBookingResponse\x12-\n" +
	"\abooking\x18\x01 \x01(\v2\x13.api.ParkingBookingR\abooking\"e\n" +
	"\x1dGetParkingBookingsListRequest\x12\x16\n" +
	"\x06filter\x18\x01 \x01(\tR\x06filter\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x03R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x03R\x06offset\"g\n" +
	"\x1eGetParkingBookingsListResponse\x12/\n" +
	"\bbookings\x18\x01 \x03(\v2\x13.api.ParkingBookingR\bbookings\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total2\xda\x02\n" +
	"\n" +
	"BookingAPI\x12h\n" +
	"\x11AddParkingBooking\x12\x1d.api.AddParkingBookingRequest\x1a\x1e.api.AddParkingBookingResponse\"\x14\x82\xd3\xe4\x93\x02\x0e\"\f/booking/add\x12h\n" +
	"\x11GetParkingBooking\x12\x1d.api.GetParkingBookingRequest\x1a\x1e.api.GetParkingBookingResponse\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/booking/get\x12x\n" +
	"\x16GetParkingBookingsList\x12\".api.GetParkingBookingsListRequest\x1a#.api.GetParkingBookingsListResponse\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/booking/listB%Z#internal/pb/parking_lot;parking_lotb\x06proto3"

var (
	file_booking_proto_rawDescOnce sync.Once
	file_booking_proto_rawDescData []byte
)

func file_booking_proto_rawDescGZIP() []byte {
	file_booking_proto_rawDescOnce.Do(func() {
		file_booking_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_booking_proto_rawDesc), len(file_booking_proto_rawDesc)))
	})
	return file_booking_proto_rawDescData
}

var file_booking_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_booking_proto_goTypes = []any{
	(*ParkingBooking)(nil),                 // 0: api.ParkingBooking
	(*AddParkingBookingRequest)(nil),       // 1: api.AddParkingBookingRequest
	(*AddParkingBookingResponse)(nil),      // 2: api.AddParkingBookingResponse
	(*GetParkingBookingRequest)(nil),       // 3: api.GetParkingBookingRequest
	(*GetParkingBookingResponse)(nil),      // 4: api.GetParkingBookingResponse
	(*GetParkingBookingsListRequest)(nil),  // 5: api.GetParkingBookingsListRequest
	(*GetParkingBookingsListResponse)(nil), // 6: api.GetParkingBookingsListResponse
	(*timestamppb.Timestamp)(nil),          // 7: google.protobuf.Timestamp
}
var file_booking_proto_depIdxs = []int32{
	7, // 0: api.ParkingBooking.time_from:type_name -> google.protobuf.Timestamp
	7, // 1: api.ParkingBooking.time_to:type_name -> google.protobuf.Timestamp
	0, // 2: api.AddParkingBookingRequest.booking:type_name -> api.ParkingBooking
	0, // 3: api.GetParkingBookingResponse.booking:type_name -> api.ParkingBooking
	0, // 4: api.GetParkingBookingsListResponse.bookings:type_name -> api.ParkingBooking
	1, // 5: api.BookingAPI.AddParkingBooking:input_type -> api.AddParkingBookingRequest
	3, // 6: api.BookingAPI.GetParkingBooking:input_type -> api.GetParkingBookingRequest
	5, // 7: api.BookingAPI.GetParkingBookingsList:input_type -> api.GetParkingBookingsListRequest
	2, // 8: api.BookingAPI.AddParkingBooking:output_type -> api.AddParkingBookingResponse
	4, // 9: api.BookingAPI.GetParkingBooking:output_type -> api.GetParkingBookingResponse
	6, // 10: api.BookingAPI.GetParkingBookingsList:output_type -> api.GetParkingBookingsListResponse
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_booking_proto_init() }
func file_booking_proto_init() {
	if File_booking_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_booking_proto_rawDesc), len(file_booking_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_booking_proto_goTypes,
		DependencyIndexes: file_booking_proto_depIdxs,
		MessageInfos:      file_booking_proto_msgTypes,
	}.Build()
	File_booking_proto = out.File
	file_booking_proto_goTypes = nil
	file_booking_proto_depIdxs = nil
}
