// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: parking.proto

package parking_lot

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ParkingKind int32

const (
	ParkingKind_UNDEFINED_PARKING_KIND ParkingKind = 0
	ParkingKind_REGULAR_PARKING_KIND   ParkingKind = 1
	ParkingKind_SPECIAL_PARKING_KIND   ParkingKind = 2
	ParkingKind_INCLUSIVE_PARKING_KIND ParkingKind = 3
)

// Enum value maps for ParkingKind.
var (
	ParkingKind_name = map[int32]string{
		0: "UNDEFINED_PARKING_KIND",
		1: "REGULAR_PARKING_KIND",
		2: "SPECIAL_PARKING_KIND",
		3: "INCLUSIVE_PARKING_KIND",
	}
	ParkingKind_value = map[string]int32{
		"UNDEFINED_PARKING_KIND": 0,
		"REGULAR_PARKING_KIND":   1,
		"SPECIAL_PARKING_KIND":   2,
		"INCLUSIVE_PARKING_KIND": 3,
	}
)

func (x ParkingKind) Enum() *ParkingKind {
	p := new(ParkingKind)
	*p = x
	return p
}

func (x ParkingKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ParkingKind) Descriptor() protoreflect.EnumDescriptor {
	return file_parking_proto_enumTypes[0].Descriptor()
}

func (ParkingKind) Type() protoreflect.EnumType {
	return &file_parking_proto_enumTypes[0]
}

func (x ParkingKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ParkingKind.Descriptor instead.
func (ParkingKind) EnumDescriptor() ([]byte, []int) {
	return file_parking_proto_rawDescGZIP(), []int{0}
}

type ParkingLotStatus int32

const (
	ParkingLotStatus_UNDEFINED_PARKING_LOT_STATUS ParkingLotStatus = 0
	ParkingLotStatus_FREE_PARKING_LOT_STATUS      ParkingLotStatus = 1
	ParkingLotStatus_BUSY_PARKING_LOT_STATUS      ParkingLotStatus = 2
	ParkingLotStatus_MINE_PARKING_LOT_STATUS      ParkingLotStatus = 3
	ParkingLotStatus_EXPIRED_PARKING_LOT_STATUS   ParkingLotStatus = 4
)

// Enum value maps for ParkingLotStatus.
var (
	ParkingLotStatus_name = map[int32]string{
		0: "UNDEFINED_PARKING_LOT_STATUS",
		1: "FREE_PARKING_LOT_STATUS",
		2: "BUSY_PARKING_LOT_STATUS",
		3: "MINE_PARKING_LOT_STATUS",
		4: "EXPIRED_PARKING_LOT_STATUS",
	}
	ParkingLotStatus_value = map[string]int32{
		"UNDEFINED_PARKING_LOT_STATUS": 0,
		"FREE_PARKING_LOT_STATUS":      1,
		"BUSY_PARKING_LOT_STATUS":      2,
		"MINE_PARKING_LOT_STATUS":      3,
		"EXPIRED_PARKING_LOT_STATUS":   4,
	}
)

func (x ParkingLotStatus) Enum() *ParkingLotStatus {
	p := new(ParkingLotStatus)
	*p = x
	return p
}

func (x ParkingLotStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ParkingLotStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_parking_proto_enumTypes[1].Descriptor()
}

func (ParkingLotStatus) Type() protoreflect.EnumType {
	return &file_parking_proto_enumTypes[1]
}

func (x ParkingLotStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ParkingLotStatus.Descriptor instead.
func (ParkingLotStatus) EnumDescriptor() ([]byte, []int) {
	return file_parking_proto_rawDescGZIP(), []int{1}
}

type ParkingType int32

const (
	ParkingType_UNDEFINED_PARKING_TYPE                ParkingType = 0
	ParkingType_OWNED_PARKING_TYPE                    ParkingType = 1
	ParkingType_LONG_TERM_RENT_BY_ME_PARKING_TYPE     ParkingType = 2
	ParkingType_SHORT_TERM_RENT_BY_ME_PARKING_TYPE    ParkingType = 3
	ParkingType_LONG_TERM_RENT_BY_OTHER_PARKING_TYPE  ParkingType = 4
	ParkingType_SHORT_TERM_RENT_BY_OTHER_PARKING_TYPE ParkingType = 5
)

// Enum value maps for ParkingType.
var (
	ParkingType_name = map[int32]string{
		0: "UNDEFINED_PARKING_TYPE",
		1: "OWNED_PARKING_TYPE",
		2: "LONG_TERM_RENT_BY_ME_PARKING_TYPE",
		3: "SHORT_TERM_RENT_BY_ME_PARKING_TYPE",
		4: "LONG_TERM_RENT_BY_OTHER_PARKING_TYPE",
		5: "SHORT_TERM_RENT_BY_OTHER_PARKING_TYPE",
	}
	ParkingType_value = map[string]int32{
		"UNDEFINED_PARKING_TYPE":                0,
		"OWNED_PARKING_TYPE":                    1,
		"LONG_TERM_RENT_BY_ME_PARKING_TYPE":     2,
		"SHORT_TERM_RENT_BY_ME_PARKING_TYPE":    3,
		"LONG_TERM_RENT_BY_OTHER_PARKING_TYPE":  4,
		"SHORT_TERM_RENT_BY_OTHER_PARKING_TYPE": 5,
	}
)

func (x ParkingType) Enum() *ParkingType {
	p := new(ParkingType)
	*p = x
	return p
}

func (x ParkingType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ParkingType) Descriptor() protoreflect.EnumDescriptor {
	return file_parking_proto_enumTypes[2].Descriptor()
}

func (ParkingType) Type() protoreflect.EnumType {
	return &file_parking_proto_enumTypes[2]
}

func (x ParkingType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ParkingType.Descriptor instead.
func (ParkingType) EnumDescriptor() ([]byte, []int) {
	return file_parking_proto_rawDescGZIP(), []int{2}
}

type UserType int32

const (
	// Неизвестный
	UserType_UNDEFINED_USER_TYPE UserType = 0
	// Обычный пользователь (Владелец+Арендатор)
	UserType_REGULAR_USER_TYPE UserType = 1
	// Управляющая компания
	UserType_MANAGING_COMPANY_USER_TYPE UserType = 2
	// Администратор
	UserType_ADMINISTRATOR_USER_TYPE UserType = 3
)

// Enum value maps for UserType.
var (
	UserType_name = map[int32]string{
		0: "UNDEFINED_USER_TYPE",
		1: "REGULAR_USER_TYPE",
		2: "MANAGING_COMPANY_USER_TYPE",
		3: "ADMINISTRATOR_USER_TYPE",
	}
	UserType_value = map[string]int32{
		"UNDEFINED_USER_TYPE":        0,
		"REGULAR_USER_TYPE":          1,
		"MANAGING_COMPANY_USER_TYPE": 2,
		"ADMINISTRATOR_USER_TYPE":    3,
	}
)

func (x UserType) Enum() *UserType {
	p := new(UserType)
	*p = x
	return p
}

func (x UserType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserType) Descriptor() protoreflect.EnumDescriptor {
	return file_parking_proto_enumTypes[3].Descriptor()
}

func (UserType) Type() protoreflect.EnumType {
	return &file_parking_proto_enumTypes[3]
}

func (x UserType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserType.Descriptor instead.
func (UserType) EnumDescriptor() ([]byte, []int) {
	return file_parking_proto_rawDescGZIP(), []int{3}
}

type AddRentalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rental        *Rental                `protobuf:"bytes,1,opt,name=rental,proto3" json:"rental,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddRentalRequest) Reset() {
	*x = AddRentalRequest{}
	mi := &file_parking_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddRentalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRentalRequest) ProtoMessage() {}

func (x *AddRentalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_parking_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRentalRequest.ProtoReflect.Descriptor instead.
func (*AddRentalRequest) Descriptor() ([]byte, []int) {
	return file_parking_proto_rawDescGZIP(), []int{0}
}

func (x *AddRentalRequest) GetRental() *Rental {
	if x != nil {
		return x.Rental
	}
	return nil
}

type AddRentalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParkingLotId  int64                  `protobuf:"varint,1,opt,name=parking_lot_id,json=parkingLotId,proto3" json:"parking_lot_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddRentalResponse) Reset() {
	*x = AddRentalResponse{}
	mi := &file_parking_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddRentalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRentalResponse) ProtoMessage() {}

func (x *AddRentalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_parking_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRentalResponse.ProtoReflect.Descriptor instead.
func (*AddRentalResponse) Descriptor() ([]byte, []int) {
	return file_parking_proto_rawDescGZIP(), []int{1}
}

func (x *AddRentalResponse) GetParkingLotId() int64 {
	if x != nil {
		return x.ParkingLotId
	}
	return 0
}

type GetMyParkingLotsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filter        *Filter                `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMyParkingLotsRequest) Reset() {
	*x = GetMyParkingLotsRequest{}
	mi := &file_parking_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMyParkingLotsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyParkingLotsRequest) ProtoMessage() {}

func (x *GetMyParkingLotsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_parking_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyParkingLotsRequest.ProtoReflect.Descriptor instead.
func (*GetMyParkingLotsRequest) Descriptor() ([]byte, []int) {
	return file_parking_proto_rawDescGZIP(), []int{2}
}

func (x *GetMyParkingLotsRequest) GetFilter() *Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

type GetMyParkingLotsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bookings      []*ParkingBooking      `protobuf:"bytes,1,rep,name=bookings,proto3" json:"bookings,omitempty"`
	Rentals       []*Rental              `protobuf:"bytes,2,rep,name=rentals,proto3" json:"rentals,omitempty"`
	ParkingLots   []*ParkingLot          `protobuf:"bytes,3,rep,name=parking_lots,json=parkingLots,proto3" json:"parking_lots,omitempty"`
	Total         int64                  `protobuf:"varint,5,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMyParkingLotsResponse) Reset() {
	*x = GetMyParkingLotsResponse{}
	mi := &file_parking_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMyParkingLotsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyParkingLotsResponse) ProtoMessage() {}

func (x *GetMyParkingLotsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_parking_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyParkingLotsResponse.ProtoReflect.Descriptor instead.
func (*GetMyParkingLotsResponse) Descriptor() ([]byte, []int) {
	return file_parking_proto_rawDescGZIP(), []int{3}
}

func (x *GetMyParkingLotsResponse) GetBookings() []*ParkingBooking {
	if x != nil {
		return x.Bookings
	}
	return nil
}

func (x *GetMyParkingLotsResponse) GetRentals() []*Rental {
	if x != nil {
		return x.Rentals
	}
	return nil
}

func (x *GetMyParkingLotsResponse) GetParkingLots() []*ParkingLot {
	if x != nil {
		return x.ParkingLots
	}
	return nil
}

func (x *GetMyParkingLotsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetUserByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByIDRequest) Reset() {
	*x = GetUserByIDRequest{}
	mi := &file_parking_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByIDRequest) ProtoMessage() {}

func (x *GetUserByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_parking_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByIDRequest.ProtoReflect.Descriptor instead.
func (*GetUserByIDRequest) Descriptor() ([]byte, []int) {
	return file_parking_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserByIDRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByIDResponse) Reset() {
	*x = GetUserByIDResponse{}
	mi := &file_parking_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByIDResponse) ProtoMessage() {}

func (x *GetUserByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_parking_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByIDResponse.ProtoReflect.Descriptor instead.
func (*GetUserByIDResponse) Descriptor() ([]byte, []int) {
	return file_parking_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserByIDResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type RegisterRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Номер телефона
	PhoneNumber string `protobuf:"bytes,1,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	// Пароль
	Password      string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_parking_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_parking_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_parking_proto_rawDescGZIP(), []int{6}
}

func (x *RegisterRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RegisterResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID пользователя в формате UUID
	UserId        string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_parking_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_parking_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_parking_proto_rawDescGZIP(), []int{7}
}

func (x *RegisterResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type LoginRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Номер телефона
	PhoneNumber string `protobuf:"bytes,1,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	// Пароль
	Password      string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_parking_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_parking_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_parking_proto_rawDescGZIP(), []int{8}
}

func (x *LoginRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Авторизационный токен
	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	// ID пользователя в виде UUID
	UserID        string `protobuf:"bytes,2,opt,name=userID,proto3" json:"userID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_parking_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_parking_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_parking_proto_rawDescGZIP(), []int{9}
}

func (x *LoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginResponse) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

type IsAdminRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID пользователя в формате UUID
	UserId        string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsAdminRequest) Reset() {
	*x = IsAdminRequest{}
	mi := &file_parking_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsAdminRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsAdminRequest) ProtoMessage() {}

func (x *IsAdminRequest) ProtoReflect() protoreflect.Message {
	mi := &file_parking_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsAdminRequest.ProtoReflect.Descriptor instead.
func (*IsAdminRequest) Descriptor() ([]byte, []int) {
	return file_parking_proto_rawDescGZIP(), []int{10}
}

func (x *IsAdminRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type IsAdminResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsAdmin       bool                   `protobuf:"varint,1,opt,name=is_admin,json=isAdmin,proto3" json:"is_admin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsAdminResponse) Reset() {
	*x = IsAdminResponse{}
	mi := &file_parking_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsAdminResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsAdminResponse) ProtoMessage() {}

func (x *IsAdminResponse) ProtoReflect() protoreflect.Message {
	mi := &file_parking_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsAdminResponse.ProtoReflect.Descriptor instead.
func (*IsAdminResponse) Descriptor() ([]byte, []int) {
	return file_parking_proto_rawDescGZIP(), []int{11}
}

func (x *IsAdminResponse) GetIsAdmin() bool {
	if x != nil {
		return x.IsAdmin
	}
	return false
}

type GetParkingLotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Number        int64                  `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	ClientId      string                 `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetParkingLotRequest) Reset() {
	*x = GetParkingLotRequest{}
	mi := &file_parking_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetParkingLotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetParkingLotRequest) ProtoMessage() {}

func (x *GetParkingLotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_parking_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetParkingLotRequest.ProtoReflect.Descriptor instead.
func (*GetParkingLotRequest) Descriptor() ([]byte, []int) {
	return file_parking_proto_rawDescGZIP(), []int{12}
}

func (x *GetParkingLotRequest) GetNumber() int64 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *GetParkingLotRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type GetParkingLotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParkingLot    *ParkingLot            `protobuf:"bytes,1,opt,name=parking_lot,json=parkingLot,proto3" json:"parking_lot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetParkingLotResponse) Reset() {
	*x = GetParkingLotResponse{}
	mi := &file_parking_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetParkingLotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetParkingLotResponse) ProtoMessage() {}

func (x *GetParkingLotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_parking_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetParkingLotResponse.ProtoReflect.Descriptor instead.
func (*GetParkingLotResponse) Descriptor() ([]byte, []int) {
	return file_parking_proto_rawDescGZIP(), []int{13}
}

func (x *GetParkingLotResponse) GetParkingLot() *ParkingLot {
	if x != nil {
		return x.ParkingLot
	}
	return nil
}

type GetParkingLotsByUserIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetParkingLotsByUserIDRequest) Reset() {
	*x = GetParkingLotsByUserIDRequest{}
	mi := &file_parking_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetParkingLotsByUserIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetParkingLotsByUserIDRequest) ProtoMessage() {}

func (x *GetParkingLotsByUserIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_parking_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetParkingLotsByUserIDRequest.ProtoReflect.Descriptor instead.
func (*GetParkingLotsByUserIDRequest) Descriptor() ([]byte, []int) {
	return file_parking_proto_rawDescGZIP(), []int{14}
}

func (x *GetParkingLotsByUserIDRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetParkingLotsByUserIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParkingLot    []*ParkingLot          `protobuf:"bytes,1,rep,name=parking_lot,json=parkingLot,proto3" json:"parking_lot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetParkingLotsByUserIDResponse) Reset() {
	*x = GetParkingLotsByUserIDResponse{}
	mi := &file_parking_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetParkingLotsByUserIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetParkingLotsByUserIDResponse) ProtoMessage() {}

func (x *GetParkingLotsByUserIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_parking_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetParkingLotsByUserIDResponse.ProtoReflect.Descriptor instead.
func (*GetParkingLotsByUserIDResponse) Descriptor() ([]byte, []int) {
	return file_parking_proto_rawDescGZIP(), []int{15}
}

func (x *GetParkingLotsByUserIDResponse) GetParkingLot() []*ParkingLot {
	if x != nil {
		return x.ParkingLot
	}
	return nil
}

type ListParkingLotsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListParkingLotsRequest) Reset() {
	*x = ListParkingLotsRequest{}
	mi := &file_parking_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListParkingLotsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListParkingLotsRequest) ProtoMessage() {}

func (x *ListParkingLotsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_parking_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListParkingLotsRequest.ProtoReflect.Descriptor instead.
func (*ListParkingLotsRequest) Descriptor() ([]byte, []int) {
	return file_parking_proto_rawDescGZIP(), []int{16}
}

func (x *ListParkingLotsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ListParkingLotsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParkingLot    []*ParkingLot          `protobuf:"bytes,1,rep,name=parking_lot,json=parkingLot,proto3" json:"parking_lot,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListParkingLotsResponse) Reset() {
	*x = ListParkingLotsResponse{}
	mi := &file_parking_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListParkingLotsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListParkingLotsResponse) ProtoMessage() {}

func (x *ListParkingLotsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_parking_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListParkingLotsResponse.ProtoReflect.Descriptor instead.
func (*ListParkingLotsResponse) Descriptor() ([]byte, []int) {
	return file_parking_proto_rawDescGZIP(), []int{17}
}

func (x *ListParkingLotsResponse) GetParkingLot() []*ParkingLot {
	if x != nil {
		return x.ParkingLot
	}
	return nil
}

func (x *ListParkingLotsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type ParkingLot struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Номер парковочного места
	Number int64 `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	// Вид парковочного места (обычное, спец., ОВЗ)
	Kind ParkingKind `protobuf:"varint,2,opt,name=kind,proto3,enum=api.ParkingKind" json:"kind,omitempty"`
	// Занятость парковочного места
	Type ParkingType `protobuf:"varint,3,opt,name=type,proto3,enum=api.ParkingType" json:"type,omitempty"`
	// Статус парковочного места
	Status ParkingLotStatus `protobuf:"varint,4,opt,name=status,proto3,enum=api.ParkingLotStatus" json:"status,omitempty"`
	// Гос. номер машины на парковочном месте
	Vehicle *string `protobuf:"bytes,5,opt,name=vehicle,proto3,oneof" json:"vehicle,omitempty"`
	// Владелец парковочного места
	OwnerId       *string `protobuf:"bytes,6,opt,name=owner_id,json=ownerId,proto3,oneof" json:"owner_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParkingLot) Reset() {
	*x = ParkingLot{}
	mi := &file_parking_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParkingLot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParkingLot) ProtoMessage() {}

func (x *ParkingLot) ProtoReflect() protoreflect.Message {
	mi := &file_parking_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParkingLot.ProtoReflect.Descriptor instead.
func (*ParkingLot) Descriptor() ([]byte, []int) {
	return file_parking_proto_rawDescGZIP(), []int{18}
}

func (x *ParkingLot) GetNumber() int64 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *ParkingLot) GetKind() ParkingKind {
	if x != nil {
		return x.Kind
	}
	return ParkingKind_UNDEFINED_PARKING_KIND
}

func (x *ParkingLot) GetType() ParkingType {
	if x != nil {
		return x.Type
	}
	return ParkingType_UNDEFINED_PARKING_TYPE
}

func (x *ParkingLot) GetStatus() ParkingLotStatus {
	if x != nil {
		return x.Status
	}
	return ParkingLotStatus_UNDEFINED_PARKING_LOT_STATUS
}

func (x *ParkingLot) GetVehicle() string {
	if x != nil && x.Vehicle != nil {
		return *x.Vehicle
	}
	return ""
}

func (x *ParkingLot) GetOwnerId() string {
	if x != nil && x.OwnerId != nil {
		return *x.OwnerId
	}
	return ""
}

type User struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// UUID
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Имя
	Name *string `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	// Фамилия
	Surname *string `protobuf:"bytes,3,opt,name=surname,proto3,oneof" json:"surname,omitempty"`
	// Отчество
	Patronymic  *string `protobuf:"bytes,4,opt,name=patronymic,proto3,oneof" json:"patronymic,omitempty"`
	PhoneNumber string  `protobuf:"bytes,5,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Address     *string `protobuf:"bytes,6,opt,name=address,proto3,oneof" json:"address,omitempty"`
	// Тип пользователя
	UserType      UserType `protobuf:"varint,7,opt,name=user_type,json=userType,proto3,enum=api.UserType" json:"user_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_parking_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_parking_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_parking_proto_rawDescGZIP(), []int{19}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *User) GetSurname() string {
	if x != nil && x.Surname != nil {
		return *x.Surname
	}
	return ""
}

func (x *User) GetPatronymic() string {
	if x != nil && x.Patronymic != nil {
		return *x.Patronymic
	}
	return ""
}

func (x *User) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *User) GetAddress() string {
	if x != nil && x.Address != nil {
		return *x.Address
	}
	return ""
}

func (x *User) GetUserType() UserType {
	if x != nil {
		return x.UserType
	}
	return UserType_UNDEFINED_USER_TYPE
}

type Vehicle struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// UUID
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Гос. номер машины
	Number string `protobuf:"bytes,2,opt,name=number,proto3" json:"number,omitempty"`
	// ID владельца машины
	UserId        string `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vehicle) Reset() {
	*x = Vehicle{}
	mi := &file_parking_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vehicle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vehicle) ProtoMessage() {}

func (x *Vehicle) ProtoReflect() protoreflect.Message {
	mi := &file_parking_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vehicle.ProtoReflect.Descriptor instead.
func (*Vehicle) Descriptor() ([]byte, []int) {
	return file_parking_proto_rawDescGZIP(), []int{20}
}

func (x *Vehicle) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Vehicle) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *Vehicle) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ParkingBooking struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ParkingLot    int64                  `protobuf:"varint,2,opt,name=parking_lot,json=parkingLot,proto3" json:"parking_lot,omitempty"`
	Vehicle       string                 `protobuf:"bytes,3,opt,name=vehicle,proto3" json:"vehicle,omitempty"`
	TimeFrom      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=time_from,json=timeFrom,proto3" json:"time_from,omitempty"`
	TimeTo        *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=time_to,json=timeTo,proto3" json:"time_to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParkingBooking) Reset() {
	*x = ParkingBooking{}
	mi := &file_parking_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParkingBooking) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParkingBooking) ProtoMessage() {}

func (x *ParkingBooking) ProtoReflect() protoreflect.Message {
	mi := &file_parking_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParkingBooking.ProtoReflect.Descriptor instead.
func (*ParkingBooking) Descriptor() ([]byte, []int) {
	return file_parking_proto_rawDescGZIP(), []int{21}
}

func (x *ParkingBooking) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ParkingBooking) GetParkingLot() int64 {
	if x != nil {
		return x.ParkingLot
	}
	return 0
}

func (x *ParkingBooking) GetVehicle() string {
	if x != nil {
		return x.Vehicle
	}
	return ""
}

func (x *ParkingBooking) GetTimeFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.TimeFrom
	}
	return nil
}

func (x *ParkingBooking) GetTimeTo() *timestamppb.Timestamp {
	if x != nil {
		return x.TimeTo
	}
	return nil
}

type AddParkingBookingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Booking       *ParkingBooking        `protobuf:"bytes,1,opt,name=booking,proto3" json:"booking,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddParkingBookingRequest) Reset() {
	*x = AddParkingBookingRequest{}
	mi := &file_parking_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddParkingBookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddParkingBookingRequest) ProtoMessage() {}

func (x *AddParkingBookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_parking_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddParkingBookingRequest.ProtoReflect.Descriptor instead.
func (*AddParkingBookingRequest) Descriptor() ([]byte, []int) {
	return file_parking_proto_rawDescGZIP(), []int{22}
}

func (x *AddParkingBookingRequest) GetBooking() *ParkingBooking {
	if x != nil {
		return x.Booking
	}
	return nil
}

type AddParkingBookingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParkingLot    int64                  `protobuf:"varint,1,opt,name=parking_lot,json=parkingLot,proto3" json:"parking_lot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddParkingBookingResponse) Reset() {
	*x = AddParkingBookingResponse{}
	mi := &file_parking_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddParkingBookingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddParkingBookingResponse) ProtoMessage() {}

func (x *AddParkingBookingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_parking_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddParkingBookingResponse.ProtoReflect.Descriptor instead.
func (*AddParkingBookingResponse) Descriptor() ([]byte, []int) {
	return file_parking_proto_rawDescGZIP(), []int{23}
}

func (x *AddParkingBookingResponse) GetParkingLot() int64 {
	if x != nil {
		return x.ParkingLot
	}
	return 0
}

type GetParkingBookingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParkingLot    int64                  `protobuf:"varint,1,opt,name=parking_lot,json=parkingLot,proto3" json:"parking_lot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetParkingBookingRequest) Reset() {
	*x = GetParkingBookingRequest{}
	mi := &file_parking_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetParkingBookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetParkingBookingRequest) ProtoMessage() {}

func (x *GetParkingBookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_parking_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetParkingBookingRequest.ProtoReflect.Descriptor instead.
func (*GetParkingBookingRequest) Descriptor() ([]byte, []int) {
	return file_parking_proto_rawDescGZIP(), []int{24}
}

func (x *GetParkingBookingRequest) GetParkingLot() int64 {
	if x != nil {
		return x.ParkingLot
	}
	return 0
}

type GetParkingBookingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Booking       *ParkingBooking        `protobuf:"bytes,1,opt,name=booking,proto3" json:"booking,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetParkingBookingResponse) Reset() {
	*x = GetParkingBookingResponse{}
	mi := &file_parking_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetParkingBookingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetParkingBookingResponse) ProtoMessage() {}

func (x *GetParkingBookingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_parking_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetParkingBookingResponse.ProtoReflect.Descriptor instead.
func (*GetParkingBookingResponse) Descriptor() ([]byte, []int) {
	return file_parking_proto_rawDescGZIP(), []int{25}
}

func (x *GetParkingBookingResponse) GetBooking() *ParkingBooking {
	if x != nil {
		return x.Booking
	}
	return nil
}

type GetParkingBookingsListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filter        *Filter                `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	Limit         int64                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`   // opt
	Offset        int64                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"` // opt
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetParkingBookingsListRequest) Reset() {
	*x = GetParkingBookingsListRequest{}
	mi := &file_parking_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetParkingBookingsListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetParkingBookingsListRequest) ProtoMessage() {}

func (x *GetParkingBookingsListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_parking_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetParkingBookingsListRequest.ProtoReflect.Descriptor instead.
func (*GetParkingBookingsListRequest) Descriptor() ([]byte, []int) {
	return file_parking_proto_rawDescGZIP(), []int{26}
}

func (x *GetParkingBookingsListRequest) GetFilter() *Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *GetParkingBookingsListRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetParkingBookingsListRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type Filter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerId       string                 `protobuf:"bytes,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	TimeFrom      *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=time_from,json=timeFrom,proto3" json:"time_from,omitempty"`
	TimeTo        *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=time_to,json=timeTo,proto3" json:"time_to,omitempty"`
	Vehicles      []string               `protobuf:"bytes,4,rep,name=vehicles,proto3" json:"vehicles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Filter) Reset() {
	*x = Filter{}
	mi := &file_parking_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filter) ProtoMessage() {}

func (x *Filter) ProtoReflect() protoreflect.Message {
	mi := &file_parking_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filter.ProtoReflect.Descriptor instead.
func (*Filter) Descriptor() ([]byte, []int) {
	return file_parking_proto_rawDescGZIP(), []int{27}
}

func (x *Filter) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *Filter) GetTimeFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.TimeFrom
	}
	return nil
}

func (x *Filter) GetTimeTo() *timestamppb.Timestamp {
	if x != nil {
		return x.TimeTo
	}
	return nil
}

func (x *Filter) GetVehicles() []string {
	if x != nil {
		return x.Vehicles
	}
	return nil
}

type GetParkingBookingsListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bookings      []*ParkingBooking      `protobuf:"bytes,1,rep,name=bookings,proto3" json:"bookings,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetParkingBookingsListResponse) Reset() {
	*x = GetParkingBookingsListResponse{}
	mi := &file_parking_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetParkingBookingsListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetParkingBookingsListResponse) ProtoMessage() {}

func (x *GetParkingBookingsListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_parking_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetParkingBookingsListResponse.ProtoReflect.Descriptor instead.
func (*GetParkingBookingsListResponse) Descriptor() ([]byte, []int) {
	return file_parking_proto_rawDescGZIP(), []int{28}
}

func (x *GetParkingBookingsListResponse) GetBookings() []*ParkingBooking {
	if x != nil {
		return x.Bookings
	}
	return nil
}

func (x *GetParkingBookingsListResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type UpdateUserRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// UUID клиента у которого изменить данные
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Имя
	Name *string `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	// Фамилия
	Surname *string `protobuf:"bytes,3,opt,name=surname,proto3,oneof" json:"surname,omitempty"`
	// Отчество
	Patronymic    *string `protobuf:"bytes,4,opt,name=patronymic,proto3,oneof" json:"patronymic,omitempty"`
	PhoneNumber   *string `protobuf:"bytes,5,opt,name=phone_number,json=phoneNumber,proto3,oneof" json:"phone_number,omitempty"`
	Address       *string `protobuf:"bytes,6,opt,name=address,proto3,oneof" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_parking_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_parking_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_parking_proto_rawDescGZIP(), []int{29}
}

func (x *UpdateUserRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateUserRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateUserRequest) GetSurname() string {
	if x != nil && x.Surname != nil {
		return *x.Surname
	}
	return ""
}

func (x *UpdateUserRequest) GetPatronymic() string {
	if x != nil && x.Patronymic != nil {
		return *x.Patronymic
	}
	return ""
}

func (x *UpdateUserRequest) GetPhoneNumber() string {
	if x != nil && x.PhoneNumber != nil {
		return *x.PhoneNumber
	}
	return ""
}

func (x *UpdateUserRequest) GetAddress() string {
	if x != nil && x.Address != nil {
		return *x.Address
	}
	return ""
}

type UpdateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserResponse) Reset() {
	*x = UpdateUserResponse{}
	mi := &file_parking_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserResponse) ProtoMessage() {}

func (x *UpdateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_parking_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserResponse.ProtoReflect.Descriptor instead.
func (*UpdateUserResponse) Descriptor() ([]byte, []int) {
	return file_parking_proto_rawDescGZIP(), []int{30}
}

type UpdateParkingLotRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Number int64                  `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	// Тип парковочного места: обычное, для лиц с ОВЗ, спец. назначения
	Kind *ParkingKind `protobuf:"varint,2,opt,name=kind,proto3,enum=api.ParkingKind,oneof" json:"kind,omitempty"`
	// Владелец парковочного места. UUID
	OwnerId *string `protobuf:"bytes,3,opt,name=owner_id,json=ownerId,proto3,oneof" json:"owner_id,omitempty"`
	// Гос. номер Т/С
	OwnerVehicle  *string `protobuf:"bytes,4,opt,name=owner_vehicle,json=ownerVehicle,proto3,oneof" json:"owner_vehicle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateParkingLotRequest) Reset() {
	*x = UpdateParkingLotRequest{}
	mi := &file_parking_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateParkingLotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateParkingLotRequest) ProtoMessage() {}

func (x *UpdateParkingLotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_parking_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateParkingLotRequest.ProtoReflect.Descriptor instead.
func (*UpdateParkingLotRequest) Descriptor() ([]byte, []int) {
	return file_parking_proto_rawDescGZIP(), []int{31}
}

func (x *UpdateParkingLotRequest) GetNumber() int64 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *UpdateParkingLotRequest) GetKind() ParkingKind {
	if x != nil && x.Kind != nil {
		return *x.Kind
	}
	return ParkingKind_UNDEFINED_PARKING_KIND
}

func (x *UpdateParkingLotRequest) GetOwnerId() string {
	if x != nil && x.OwnerId != nil {
		return *x.OwnerId
	}
	return ""
}

func (x *UpdateParkingLotRequest) GetOwnerVehicle() string {
	if x != nil && x.OwnerVehicle != nil {
		return *x.OwnerVehicle
	}
	return ""
}

type UpdateParkingLotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateParkingLotResponse) Reset() {
	*x = UpdateParkingLotResponse{}
	mi := &file_parking_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateParkingLotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateParkingLotResponse) ProtoMessage() {}

func (x *UpdateParkingLotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_parking_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateParkingLotResponse.ProtoReflect.Descriptor instead.
func (*UpdateParkingLotResponse) Descriptor() ([]byte, []int) {
	return file_parking_proto_rawDescGZIP(), []int{32}
}

type Rental struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RentalId      string                 `protobuf:"bytes,1,opt,name=rental_id,json=rentalId,proto3" json:"rental_id,omitempty"`
	ParkingLot    int64                  `protobuf:"varint,2,opt,name=parking_lot,json=parkingLot,proto3" json:"parking_lot,omitempty"`
	TimeFrom      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=time_from,json=timeFrom,proto3" json:"time_from,omitempty"`
	TimeTo        *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=time_to,json=timeTo,proto3" json:"time_to,omitempty"`
	CostPerHour   int64                  `protobuf:"varint,6,opt,name=cost_per_hour,json=costPerHour,proto3" json:"cost_per_hour,omitempty"`
	CostPerDay    int64                  `protobuf:"varint,7,opt,name=cost_per_day,json=costPerDay,proto3" json:"cost_per_day,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rental) Reset() {
	*x = Rental{}
	mi := &file_parking_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rental) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rental) ProtoMessage() {}

func (x *Rental) ProtoReflect() protoreflect.Message {
	mi := &file_parking_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rental.ProtoReflect.Descriptor instead.
func (*Rental) Descriptor() ([]byte, []int) {
	return file_parking_proto_rawDescGZIP(), []int{33}
}

func (x *Rental) GetRentalId() string {
	if x != nil {
		return x.RentalId
	}
	return ""
}

func (x *Rental) GetParkingLot() int64 {
	if x != nil {
		return x.ParkingLot
	}
	return 0
}

func (x *Rental) GetTimeFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.TimeFrom
	}
	return nil
}

func (x *Rental) GetTimeTo() *timestamppb.Timestamp {
	if x != nil {
		return x.TimeTo
	}
	return nil
}

func (x *Rental) GetCostPerHour() int64 {
	if x != nil {
		return x.CostPerHour
	}
	return 0
}

func (x *Rental) GetCostPerDay() int64 {
	if x != nil {
		return x.CostPerDay
	}
	return 0
}

var File_parking_proto protoreflect.FileDescriptor

const file_parking_proto_rawDesc = "" +
	"\n" +
	"\rparking.proto\x12\x03api\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"7\n" +
	"\x10AddRentalRequest\x12#\n" +
	"\x06rental\x18\x01 \x01(\v2\v.api.RentalR\x06rental\"9\n" +
	"\x11AddRentalResponse\x12$\n" +
	"\x0eparking_lot_id\x18\x01 \x01(\x03R\fparkingLotId\">\n" +
	"\x17GetMyParkingLotsRequest\x12#\n" +
	"\x06filter\x18\x01 \x01(\v2\v.api.FilterR\x06filter\"\xbc\x01\n" +
	"\x18GetMyParkingLotsResponse\x12/\n" +
	"\bbookings\x18\x01 \x03(\v2\x13.api.ParkingBookingR\bbookings\x12%\n" +
	"\arentals\x18\x02 \x03(\v2\v.api.RentalR\arentals\x122\n" +
	"\fparking_lots\x18\x03 \x03(\v2\x0f.api.ParkingLotR\vparkingLots\x12\x14\n" +
	"\x05total\x18\x05 \x01(\x03R\x05total\"2\n" +
	"\x12GetUserByIDRequest\x12\x1c\n" +
	"\auser_id\x18\x01 \x01(\tB\x03\xe0A\x02R\x06userId\"4\n" +
	"\x13GetUserByIDResponse\x12\x1d\n" +
	"\x04user\x18\x01 \x01(\v2\t.api.UserR\x04user\"P\n" +
	"\x0fRegisterRequest\x12!\n" +
	"\fphone_number\x18\x01 \x01(\tR\vphoneNumber\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"+\n" +
	"\x10RegisterResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"M\n" +
	"\fLoginRequest\x12!\n" +
	"\fphone_number\x18\x01 \x01(\tR\vphoneNumber\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"=\n" +
	"\rLoginResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x16\n" +
	"\x06userID\x18\x02 \x01(\tR\x06userID\")\n" +
	"\x0eIsAdminRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\",\n" +
	"\x0fIsAdminResponse\x12\x19\n" +
	"\bis_admin\x18\x01 \x01(\bR\aisAdmin\"K\n" +
	"\x14GetParkingLotRequest\x12\x16\n" +
	"\x06number\x18\x01 \x01(\x03R\x06number\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\"I\n" +
	"\x15GetParkingLotResponse\x120\n" +
	"\vparking_lot\x18\x01 \x01(\v2\x0f.api.ParkingLotR\n" +
	"parkingLot\"8\n" +
	"\x1dGetParkingLotsByUserIDRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"R\n" +
	"\x1eGetParkingLotsByUserIDResponse\x120\n" +
	"\vparking_lot\x18\x01 \x03(\v2\x0f.api.ParkingLotR\n" +
	"parkingLot\"1\n" +
	"\x16ListParkingLotsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"a\n" +
	"\x17ListParkingLotsResponse\x120\n" +
	"\vparking_lot\x18\x01 \x03(\v2\x0f.api.ParkingLotR\n" +
	"parkingLot\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\xf7\x01\n" +
	"\n" +
	"ParkingLot\x12\x16\n" +
	"\x06number\x18\x01 \x01(\x03R\x06number\x12$\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x10.api.ParkingKindR\x04kind\x12$\n" +
	"\x04type\x18\x03 \x01(\x0e2\x10.api.ParkingTypeR\x04type\x12-\n" +
	"\x06status\x18\x04 \x01(\x0e2\x15.api.ParkingLotStatusR\x06status\x12\x1d\n" +
	"\avehicle\x18\x05 \x01(\tH\x00R\avehicle\x88\x01\x01\x12\x1e\n" +
	"\bowner_id\x18\x06 \x01(\tH\x01R\aownerId\x88\x01\x01B\n" +
	"\n" +
	"\b_vehicleB\v\n" +
	"\t_owner_id\"\x91\x02\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x1d\n" +
	"\asurname\x18\x03 \x01(\tH\x01R\asurname\x88\x01\x01\x12#\n" +
	"\n" +
	"patronymic\x18\x04 \x01(\tH\x02R\n" +
	"patronymic\x88\x01\x01\x12!\n" +
	"\fphone_number\x18\x05 \x01(\tR\vphoneNumber\x12\x1d\n" +
	"\aaddress\x18\x06 \x01(\tH\x03R\aaddress\x88\x01\x01\x12*\n" +
	"\tuser_type\x18\a \x01(\x0e2\r.api.UserTypeR\buserTypeB\a\n" +
	"\x05_nameB\n" +
	"\n" +
	"\b_surnameB\r\n" +
	"\v_patronymicB\n" +
	"\n" +
	"\b_address\"J\n" +
	"\aVehicle\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06number\x18\x02 \x01(\tR\x06number\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\"\xe1\x01\n" +
	"\x0eParkingBooking\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1f\n" +
	"\vparking_lot\x18\x02 \x01(\x03R\n" +
	"parkingLot\x12\x1d\n" +
	"\avehicle\x18\x03 \x01(\tB\x03\xe0A\x02R\avehicle\x12<\n" +
	"\ttime_from\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x02R\btimeFrom\x128\n" +
	"\atime_to\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x02R\x06timeTo\"N\n" +
	"\x18AddParkingBookingRequest\x122\n" +
	"\abooking\x18\x01 \x01(\v2\x13.api.ParkingBookingB\x03\xe0A\x02R\abooking\"<\n" +
	"\x19AddParkingBookingResponse\x12\x1f\n" +
	"\vparking_lot\x18\x01 \x01(\x03R\n" +
	"parkingLot\";\n" +
	"\x18GetParkingBookingRequest\x12\x1f\n" +
	"\vparking_lot\x18\x01 \x01(\x03R\n" +
	"parkingLot\"J\n" +
	"\x19GetParkingBookingResponse\x12-\n" +
	"\abooking\x18\x01 \x01(\v2\x13.api.ParkingBookingR\abooking\"r\n" +
	"\x1dGetParkingBookingsListRequest\x12#\n" +
	"\x06filter\x18\x01 \x01(\v2\v.api.FilterR\x06filter\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x03R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x03R\x06offset\"\xb2\x01\n" +
	"\x06Filter\x12\x1e\n" +
	"\bowner_id\x18\x01 \x01(\tB\x03\xe0A\x02R\aownerId\x127\n" +
	"\ttime_from\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\btimeFrom\x123\n" +
	"\atime_to\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x06timeTo\x12\x1a\n" +
	"\bvehicles\x18\x04 \x03(\tR\bvehicles\"g\n" +
	"\x1eGetParkingBookingsListResponse\x12/\n" +
	"\bbookings\x18\x01 \x03(\v2\x13.api.ParkingBookingR\bbookings\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\x88\x02\n" +
	"\x11UpdateUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x1d\n" +
	"\asurname\x18\x03 \x01(\tH\x01R\asurname\x88\x01\x01\x12#\n" +
	"\n" +
	"patronymic\x18\x04 \x01(\tH\x02R\n" +
	"patronymic\x88\x01\x01\x12&\n" +
	"\fphone_number\x18\x05 \x01(\tH\x03R\vphoneNumber\x88\x01\x01\x12\x1d\n" +
	"\aaddress\x18\x06 \x01(\tH\x04R\aaddress\x88\x01\x01B\a\n" +
	"\x05_nameB\n" +
	"\n" +
	"\b_surnameB\r\n" +
	"\v_patronymicB\x0f\n" +
	"\r_phone_numberB\n" +
	"\n" +
	"\b_address\"\x14\n" +
	"\x12UpdateUserResponse\"\xce\x01\n" +
	"\x17UpdateParkingLotRequest\x12\x16\n" +
	"\x06number\x18\x01 \x01(\x03R\x06number\x12)\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x10.api.ParkingKindH\x00R\x04kind\x88\x01\x01\x12\x1e\n" +
	"\bowner_id\x18\x03 \x01(\tH\x01R\aownerId\x88\x01\x01\x12(\n" +
	"\rowner_vehicle\x18\x04 \x01(\tH\x02R\fownerVehicle\x88\x01\x01B\a\n" +
	"\x05_kindB\v\n" +
	"\t_owner_idB\x10\n" +
	"\x0e_owner_vehicle\"\x1a\n" +
	"\x18UpdateParkingLotResponse\"\x84\x02\n" +
	"\x06Rental\x12\x1b\n" +
	"\trental_id\x18\x01 \x01(\tR\brentalId\x12\x1f\n" +
	"\vparking_lot\x18\x02 \x01(\x03R\n" +
	"parkingLot\x12<\n" +
	"\ttime_from\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x02R\btimeFrom\x128\n" +
	"\atime_to\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x02R\x06timeTo\x12\"\n" +
	"\rcost_per_hour\x18\x06 \x01(\x03R\vcostPerHour\x12 \n" +
	"\fcost_per_day\x18\a \x01(\x03R\n" +
	"costPerDay*y\n" +
	"\vParkingKind\x12\x1a\n" +
	"\x16UNDEFINED_PARKING_KIND\x10\x00\x12\x18\n" +
	"\x14REGULAR_PARKING_KIND\x10\x01\x12\x18\n" +
	"\x14SPECIAL_PARKING_KIND\x10\x02\x12\x1a\n" +
	"\x16INCLUSIVE_PARKING_KIND\x10\x03*\xab\x01\n" +
	"\x10ParkingLotStatus\x12 \n" +
	"\x1cUNDEFINED_PARKING_LOT_STATUS\x10\x00\x12\x1b\n" +
	"\x17FREE_PARKING_LOT_STATUS\x10\x01\x12\x1b\n" +
	"\x17BUSY_PARKING_LOT_STATUS\x10\x02\x12\x1b\n" +
	"\x17MINE_PARKING_LOT_STATUS\x10\x03\x12\x1e\n" +
	"\x1aEXPIRED_PARKING_LOT_STATUS\x10\x04*\xe5\x01\n" +
	"\vParkingType\x12\x1a\n" +
	"\x16UNDEFINED_PARKING_TYPE\x10\x00\x12\x16\n" +
	"\x12OWNED_PARKING_TYPE\x10\x01\x12%\n" +
	"!LONG_TERM_RENT_BY_ME_PARKING_TYPE\x10\x02\x12&\n" +
	"\"SHORT_TERM_RENT_BY_ME_PARKING_TYPE\x10\x03\x12(\n" +
	"$LONG_TERM_RENT_BY_OTHER_PARKING_TYPE\x10\x04\x12)\n" +
	"%SHORT_TERM_RENT_BY_OTHER_PARKING_TYPE\x10\x05*w\n" +
	"\bUserType\x12\x17\n" +
	"\x13UNDEFINED_USER_TYPE\x10\x00\x12\x15\n" +
	"\x11REGULAR_USER_TYPE\x10\x01\x12\x1e\n" +
	"\x1aMANAGING_COMPANY_USER_TYPE\x10\x02\x12\x1b\n" +
	"\x17ADMINISTRATOR_USER_TYPE\x10\x032\x98\n" +
	"\n" +
	"\n" +
	"ParkingAPI\x12\\\n" +
	"\rGetParkingLot\x12\x19.api.GetParkingLotRequest\x1a\x1a.api.GetParkingLotResponse\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/parking/get\x12\x82\x01\n" +
	"\x16GetParkingLotsByUserID\x12\".api.GetParkingLotsByUserIDRequest\x1a#.api.GetParkingLotsByUserIDResponse\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/parking/get_by_user_id\x12c\n" +
	"\x0fListParkingLots\x12\x1b.api.ListParkingLotsRequest\x1a\x1c.api.ListParkingLotsResponse\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/parking/list\x12k\n" +
	"\x11AddParkingBooking\x12\x1d.api.AddParkingBookingRequest\x1a\x1e.api.AddParkingBookingResponse\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/booking/add\x12h\n" +
	"\x11GetParkingBooking\x12\x1d.api.GetParkingBookingRequest\x1a\x1e.api.GetParkingBookingResponse\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/booking/get\x12x\n" +
	"\x16GetParkingBookingsList\x12\".api.GetParkingBookingsListRequest\x1a#.api.GetParkingBookingsListResponse\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/booking/list\x12Q\n" +
	"\bRegister\x12\x14.api.RegisterRequest\x1a\x15.api.RegisterResponse\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/sso/register\x12E\n" +
	"\x05Login\x12\x11.api.LoginRequest\x1a\x12.api.LoginResponse\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/sso/login\x12S\n" +
	"\vGetUserByID\x12\x17.api.GetUserByIDRequest\x1a\x18.api.GetUserByIDResponse\"\x11\x82\xd3\xe4\x93\x02\v\x12\t/user/get\x12V\n" +
	"\n" +
	"UpdateUser\x12\x16.api.UpdateUserRequest\x1a\x17.api.UpdateUserResponse\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/user/update\x12k\n" +
	"\x10UpdateParkingLot\x12\x1c.api.UpdateParkingLotRequest\x1a\x1d.api.UpdateParkingLotResponse\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/parking/update\x12R\n" +
	"\tAddRental\x12\x15.api.AddRentalRequest\x1a\x16.api.AddRentalResponse\"\x16\x82\xd3\xe4\x93\x02\x10:\x01*\"\v/rental/add\x12i\n" +
	"\x10GetMyParkingLots\x12\x1c.api.GetMyParkingLotsRequest\x1a\x1d.api.GetMyParkingLotsResponse\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/my/parking/listB%Z#internal/pb/parking_lot;parking_lotb\x06proto3"

var (
	file_parking_proto_rawDescOnce sync.Once
	file_parking_proto_rawDescData []byte
)

func file_parking_proto_rawDescGZIP() []byte {
	file_parking_proto_rawDescOnce.Do(func() {
		file_parking_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_parking_proto_rawDesc), len(file_parking_proto_rawDesc)))
	})
	return file_parking_proto_rawDescData
}

var file_parking_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_parking_proto_msgTypes = make([]protoimpl.MessageInfo, 34)
var file_parking_proto_goTypes = []any{
	(ParkingKind)(0),                       // 0: api.ParkingKind
	(ParkingLotStatus)(0),                  // 1: api.ParkingLotStatus
	(ParkingType)(0),                       // 2: api.ParkingType
	(UserType)(0),                          // 3: api.UserType
	(*AddRentalRequest)(nil),               // 4: api.AddRentalRequest
	(*AddRentalResponse)(nil),              // 5: api.AddRentalResponse
	(*GetMyParkingLotsRequest)(nil),        // 6: api.GetMyParkingLotsRequest
	(*GetMyParkingLotsResponse)(nil),       // 7: api.GetMyParkingLotsResponse
	(*GetUserByIDRequest)(nil),             // 8: api.GetUserByIDRequest
	(*GetUserByIDResponse)(nil),            // 9: api.GetUserByIDResponse
	(*RegisterRequest)(nil),                // 10: api.RegisterRequest
	(*RegisterResponse)(nil),               // 11: api.RegisterResponse
	(*LoginRequest)(nil),                   // 12: api.LoginRequest
	(*LoginResponse)(nil),                  // 13: api.LoginResponse
	(*IsAdminRequest)(nil),                 // 14: api.IsAdminRequest
	(*IsAdminResponse)(nil),                // 15: api.IsAdminResponse
	(*GetParkingLotRequest)(nil),           // 16: api.GetParkingLotRequest
	(*GetParkingLotResponse)(nil),          // 17: api.GetParkingLotResponse
	(*GetParkingLotsByUserIDRequest)(nil),  // 18: api.GetParkingLotsByUserIDRequest
	(*GetParkingLotsByUserIDResponse)(nil), // 19: api.GetParkingLotsByUserIDResponse
	(*ListParkingLotsRequest)(nil),         // 20: api.ListParkingLotsRequest
	(*ListParkingLotsResponse)(nil),        // 21: api.ListParkingLotsResponse
	(*ParkingLot)(nil),                     // 22: api.ParkingLot
	(*User)(nil),                           // 23: api.User
	(*Vehicle)(nil),                        // 24: api.Vehicle
	(*ParkingBooking)(nil),                 // 25: api.ParkingBooking
	(*AddParkingBookingRequest)(nil),       // 26: api.AddParkingBookingRequest
	(*AddParkingBookingResponse)(nil),      // 27: api.AddParkingBookingResponse
	(*GetParkingBookingRequest)(nil),       // 28: api.GetParkingBookingRequest
	(*GetParkingBookingResponse)(nil),      // 29: api.GetParkingBookingResponse
	(*GetParkingBookingsListRequest)(nil),  // 30: api.GetParkingBookingsListRequest
	(*Filter)(nil),                         // 31: api.Filter
	(*GetParkingBookingsListResponse)(nil), // 32: api.GetParkingBookingsListResponse
	(*UpdateUserRequest)(nil),              // 33: api.UpdateUserRequest
	(*UpdateUserResponse)(nil),             // 34: api.UpdateUserResponse
	(*UpdateParkingLotRequest)(nil),        // 35: api.UpdateParkingLotRequest
	(*UpdateParkingLotResponse)(nil),       // 36: api.UpdateParkingLotResponse
	(*Rental)(nil),                         // 37: api.Rental
	(*timestamppb.Timestamp)(nil),          // 38: google.protobuf.Timestamp
}
var file_parking_proto_depIdxs = []int32{
	37, // 0: api.AddRentalRequest.rental:type_name -> api.Rental
	31, // 1: api.GetMyParkingLotsRequest.filter:type_name -> api.Filter
	25, // 2: api.GetMyParkingLotsResponse.bookings:type_name -> api.ParkingBooking
	37, // 3: api.GetMyParkingLotsResponse.rentals:type_name -> api.Rental
	22, // 4: api.GetMyParkingLotsResponse.parking_lots:type_name -> api.ParkingLot
	23, // 5: api.GetUserByIDResponse.user:type_name -> api.User
	22, // 6: api.GetParkingLotResponse.parking_lot:type_name -> api.ParkingLot
	22, // 7: api.GetParkingLotsByUserIDResponse.parking_lot:type_name -> api.ParkingLot
	22, // 8: api.ListParkingLotsResponse.parking_lot:type_name -> api.ParkingLot
	0,  // 9: api.ParkingLot.kind:type_name -> api.ParkingKind
	2,  // 10: api.ParkingLot.type:type_name -> api.ParkingType
	1,  // 11: api.ParkingLot.status:type_name -> api.ParkingLotStatus
	3,  // 12: api.User.user_type:type_name -> api.UserType
	38, // 13: api.ParkingBooking.time_from:type_name -> google.protobuf.Timestamp
	38, // 14: api.ParkingBooking.time_to:type_name -> google.protobuf.Timestamp
	25, // 15: api.AddParkingBookingRequest.booking:type_name -> api.ParkingBooking
	25, // 16: api.GetParkingBookingResponse.booking:type_name -> api.ParkingBooking
	31, // 17: api.GetParkingBookingsListRequest.filter:type_name -> api.Filter
	38, // 18: api.Filter.time_from:type_name -> google.protobuf.Timestamp
	38, // 19: api.Filter.time_to:type_name -> google.protobuf.Timestamp
	25, // 20: api.GetParkingBookingsListResponse.bookings:type_name -> api.ParkingBooking
	0,  // 21: api.UpdateParkingLotRequest.kind:type_name -> api.ParkingKind
	38, // 22: api.Rental.time_from:type_name -> google.protobuf.Timestamp
	38, // 23: api.Rental.time_to:type_name -> google.protobuf.Timestamp
	16, // 24: api.ParkingAPI.GetParkingLot:input_type -> api.GetParkingLotRequest
	18, // 25: api.ParkingAPI.GetParkingLotsByUserID:input_type -> api.GetParkingLotsByUserIDRequest
	20, // 26: api.ParkingAPI.ListParkingLots:input_type -> api.ListParkingLotsRequest
	26, // 27: api.ParkingAPI.AddParkingBooking:input_type -> api.AddParkingBookingRequest
	28, // 28: api.ParkingAPI.GetParkingBooking:input_type -> api.GetParkingBookingRequest
	30, // 29: api.ParkingAPI.GetParkingBookingsList:input_type -> api.GetParkingBookingsListRequest
	10, // 30: api.ParkingAPI.Register:input_type -> api.RegisterRequest
	12, // 31: api.ParkingAPI.Login:input_type -> api.LoginRequest
	8,  // 32: api.ParkingAPI.GetUserByID:input_type -> api.GetUserByIDRequest
	33, // 33: api.ParkingAPI.UpdateUser:input_type -> api.UpdateUserRequest
	35, // 34: api.ParkingAPI.UpdateParkingLot:input_type -> api.UpdateParkingLotRequest
	4,  // 35: api.ParkingAPI.AddRental:input_type -> api.AddRentalRequest
	6,  // 36: api.ParkingAPI.GetMyParkingLots:input_type -> api.GetMyParkingLotsRequest
	17, // 37: api.ParkingAPI.GetParkingLot:output_type -> api.GetParkingLotResponse
	19, // 38: api.ParkingAPI.GetParkingLotsByUserID:output_type -> api.GetParkingLotsByUserIDResponse
	21, // 39: api.ParkingAPI.ListParkingLots:output_type -> api.ListParkingLotsResponse
	27, // 40: api.ParkingAPI.AddParkingBooking:output_type -> api.AddParkingBookingResponse
	29, // 41: api.ParkingAPI.GetParkingBooking:output_type -> api.GetParkingBookingResponse
	32, // 42: api.ParkingAPI.GetParkingBookingsList:output_type -> api.GetParkingBookingsListResponse
	11, // 43: api.ParkingAPI.Register:output_type -> api.RegisterResponse
	13, // 44: api.ParkingAPI.Login:output_type -> api.LoginResponse
	9,  // 45: api.ParkingAPI.GetUserByID:output_type -> api.GetUserByIDResponse
	34, // 46: api.ParkingAPI.UpdateUser:output_type -> api.UpdateUserResponse
	36, // 47: api.ParkingAPI.UpdateParkingLot:output_type -> api.UpdateParkingLotResponse
	5,  // 48: api.ParkingAPI.AddRental:output_type -> api.AddRentalResponse
	7,  // 49: api.ParkingAPI.GetMyParkingLots:output_type -> api.GetMyParkingLotsResponse
	37, // [37:50] is the sub-list for method output_type
	24, // [24:37] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_parking_proto_init() }
func file_parking_proto_init() {
	if File_parking_proto != nil {
		return
	}
	file_parking_proto_msgTypes[18].OneofWrappers = []any{}
	file_parking_proto_msgTypes[19].OneofWrappers = []any{}
	file_parking_proto_msgTypes[29].OneofWrappers = []any{}
	file_parking_proto_msgTypes[31].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_parking_proto_rawDesc), len(file_parking_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   34,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_parking_proto_goTypes,
		DependencyIndexes: file_parking_proto_depIdxs,
		EnumInfos:         file_parking_proto_enumTypes,
		MessageInfos:      file_parking_proto_msgTypes,
	}.Build()
	File_parking_proto = out.File
	file_parking_proto_goTypes = nil
	file_parking_proto_depIdxs = nil
}
