// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: parking.proto

package parking_lot

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ParkingLotStatus int32

const (
	ParkingLotStatus_UNDEFINED_PARKING_LOT_STATUS    ParkingLotStatus = 0
	ParkingLotStatus_AVAILABLE_PARKING_LOT_STATUS    ParkingLotStatus = 1
	ParkingLotStatus_BOOKED_PARKING_LOT_STATUS       ParkingLotStatus = 2
	ParkingLotStatus_BOOKED_BY_ME_PARKING_LOT_STATUS ParkingLotStatus = 3
)

// Enum value maps for ParkingLotStatus.
var (
	ParkingLotStatus_name = map[int32]string{
		0: "UNDEFINED_PARKING_LOT_STATUS",
		1: "AVAILABLE_PARKING_LOT_STATUS",
		2: "BOOKED_PARKING_LOT_STATUS",
		3: "BOOKED_BY_ME_PARKING_LOT_STATUS",
	}
	ParkingLotStatus_value = map[string]int32{
		"UNDEFINED_PARKING_LOT_STATUS":    0,
		"AVAILABLE_PARKING_LOT_STATUS":    1,
		"BOOKED_PARKING_LOT_STATUS":       2,
		"BOOKED_BY_ME_PARKING_LOT_STATUS": 3,
	}
)

func (x ParkingLotStatus) Enum() *ParkingLotStatus {
	p := new(ParkingLotStatus)
	*p = x
	return p
}

func (x ParkingLotStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ParkingLotStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_parking_proto_enumTypes[0].Descriptor()
}

func (ParkingLotStatus) Type() protoreflect.EnumType {
	return &file_parking_proto_enumTypes[0]
}

func (x ParkingLotStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ParkingLotStatus.Descriptor instead.
func (ParkingLotStatus) EnumDescriptor() ([]byte, []int) {
	return file_parking_proto_rawDescGZIP(), []int{0}
}

type ParkingType int32

const (
	// Неизвестный тип парковочного места
	ParkingType_UNDEFINED_PARKING_TYPE ParkingType = 0
	// Тип постоянного парковочного места
	ParkingType_PERMANENT_PARKING_TYPE ParkingType = 1
	// Тип временного парковочного места
	ParkingType_RENT_PARKING_TYPE ParkingType = 2
	// Тип парковочного места для спец. назначения (скорая, пожарные и т.д.)
	ParkingType_SPECIAL_PARKING_TYPE ParkingType = 3
	// Тип парковочного места для инвалидов
	ParkingType_INCLUSIVE_PARKING_TYPE ParkingType = 4 // etc
)

// Enum value maps for ParkingType.
var (
	ParkingType_name = map[int32]string{
		0: "UNDEFINED_PARKING_TYPE",
		1: "PERMANENT_PARKING_TYPE",
		2: "RENT_PARKING_TYPE",
		3: "SPECIAL_PARKING_TYPE",
		4: "INCLUSIVE_PARKING_TYPE",
	}
	ParkingType_value = map[string]int32{
		"UNDEFINED_PARKING_TYPE": 0,
		"PERMANENT_PARKING_TYPE": 1,
		"RENT_PARKING_TYPE":      2,
		"SPECIAL_PARKING_TYPE":   3,
		"INCLUSIVE_PARKING_TYPE": 4,
	}
)

func (x ParkingType) Enum() *ParkingType {
	p := new(ParkingType)
	*p = x
	return p
}

func (x ParkingType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ParkingType) Descriptor() protoreflect.EnumDescriptor {
	return file_parking_proto_enumTypes[1].Descriptor()
}

func (ParkingType) Type() protoreflect.EnumType {
	return &file_parking_proto_enumTypes[1]
}

func (x ParkingType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ParkingType.Descriptor instead.
func (ParkingType) EnumDescriptor() ([]byte, []int) {
	return file_parking_proto_rawDescGZIP(), []int{1}
}

type UserType int32

const (
	// Неизвестный
	UserType_UNDEFINED_USER_TYPE UserType = 0
	// Обычный пользователь (Владелец+Арендатор)
	UserType_REGULAR_USER_TYPE UserType = 1
	// Управляющая компания
	UserType_MANAGING_COMPANY_USER_TYPE UserType = 2
	// Администратор
	UserType_ADMINISTRATOR_USER_TYPE UserType = 3
)

// Enum value maps for UserType.
var (
	UserType_name = map[int32]string{
		0: "UNDEFINED_USER_TYPE",
		1: "REGULAR_USER_TYPE",
		2: "MANAGING_COMPANY_USER_TYPE",
		3: "ADMINISTRATOR_USER_TYPE",
	}
	UserType_value = map[string]int32{
		"UNDEFINED_USER_TYPE":        0,
		"REGULAR_USER_TYPE":          1,
		"MANAGING_COMPANY_USER_TYPE": 2,
		"ADMINISTRATOR_USER_TYPE":    3,
	}
)

func (x UserType) Enum() *UserType {
	p := new(UserType)
	*p = x
	return p
}

func (x UserType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserType) Descriptor() protoreflect.EnumDescriptor {
	return file_parking_proto_enumTypes[2].Descriptor()
}

func (UserType) Type() protoreflect.EnumType {
	return &file_parking_proto_enumTypes[2]
}

func (x UserType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserType.Descriptor instead.
func (UserType) EnumDescriptor() ([]byte, []int) {
	return file_parking_proto_rawDescGZIP(), []int{2}
}

type GetUserByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByIDRequest) Reset() {
	*x = GetUserByIDRequest{}
	mi := &file_parking_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByIDRequest) ProtoMessage() {}

func (x *GetUserByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_parking_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByIDRequest.ProtoReflect.Descriptor instead.
func (*GetUserByIDRequest) Descriptor() ([]byte, []int) {
	return file_parking_proto_rawDescGZIP(), []int{0}
}

func (x *GetUserByIDRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByIDResponse) Reset() {
	*x = GetUserByIDResponse{}
	mi := &file_parking_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByIDResponse) ProtoMessage() {}

func (x *GetUserByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_parking_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByIDResponse.ProtoReflect.Descriptor instead.
func (*GetUserByIDResponse) Descriptor() ([]byte, []int) {
	return file_parking_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserByIDResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type RegisterRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Номер телефона
	PhoneNumber string `protobuf:"bytes,1,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	// Пароль
	Password      string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_parking_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_parking_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_parking_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RegisterResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID пользователя в формате UUID
	UserId        string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_parking_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_parking_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_parking_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type LoginRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Номер телефона
	PhoneNumber string `protobuf:"bytes,1,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	// Пароль
	Password      string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_parking_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_parking_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_parking_proto_rawDescGZIP(), []int{4}
}

func (x *LoginRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Авторизационный токен
	Token         string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	UserID        string `protobuf:"bytes,2,opt,name=userID,proto3" json:"userID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_parking_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_parking_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_parking_proto_rawDescGZIP(), []int{5}
}

func (x *LoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginResponse) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

type IsAdminRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID пользователя в формате UUID
	UserId        string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsAdminRequest) Reset() {
	*x = IsAdminRequest{}
	mi := &file_parking_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsAdminRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsAdminRequest) ProtoMessage() {}

func (x *IsAdminRequest) ProtoReflect() protoreflect.Message {
	mi := &file_parking_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsAdminRequest.ProtoReflect.Descriptor instead.
func (*IsAdminRequest) Descriptor() ([]byte, []int) {
	return file_parking_proto_rawDescGZIP(), []int{6}
}

func (x *IsAdminRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type IsAdminResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsAdmin       bool                   `protobuf:"varint,1,opt,name=is_admin,json=isAdmin,proto3" json:"is_admin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsAdminResponse) Reset() {
	*x = IsAdminResponse{}
	mi := &file_parking_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsAdminResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsAdminResponse) ProtoMessage() {}

func (x *IsAdminResponse) ProtoReflect() protoreflect.Message {
	mi := &file_parking_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsAdminResponse.ProtoReflect.Descriptor instead.
func (*IsAdminResponse) Descriptor() ([]byte, []int) {
	return file_parking_proto_rawDescGZIP(), []int{7}
}

func (x *IsAdminResponse) GetIsAdmin() bool {
	if x != nil {
		return x.IsAdmin
	}
	return false
}

type GetParkingLotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Number        int64                  `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetParkingLotRequest) Reset() {
	*x = GetParkingLotRequest{}
	mi := &file_parking_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetParkingLotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetParkingLotRequest) ProtoMessage() {}

func (x *GetParkingLotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_parking_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetParkingLotRequest.ProtoReflect.Descriptor instead.
func (*GetParkingLotRequest) Descriptor() ([]byte, []int) {
	return file_parking_proto_rawDescGZIP(), []int{8}
}

func (x *GetParkingLotRequest) GetNumber() int64 {
	if x != nil {
		return x.Number
	}
	return 0
}

type GetParkingLotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParkingLot    *ParkingLot            `protobuf:"bytes,1,opt,name=parking_lot,json=parkingLot,proto3" json:"parking_lot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetParkingLotResponse) Reset() {
	*x = GetParkingLotResponse{}
	mi := &file_parking_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetParkingLotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetParkingLotResponse) ProtoMessage() {}

func (x *GetParkingLotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_parking_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetParkingLotResponse.ProtoReflect.Descriptor instead.
func (*GetParkingLotResponse) Descriptor() ([]byte, []int) {
	return file_parking_proto_rawDescGZIP(), []int{9}
}

func (x *GetParkingLotResponse) GetParkingLot() *ParkingLot {
	if x != nil {
		return x.ParkingLot
	}
	return nil
}

type GetParkingLotsByUserIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetParkingLotsByUserIDRequest) Reset() {
	*x = GetParkingLotsByUserIDRequest{}
	mi := &file_parking_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetParkingLotsByUserIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetParkingLotsByUserIDRequest) ProtoMessage() {}

func (x *GetParkingLotsByUserIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_parking_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetParkingLotsByUserIDRequest.ProtoReflect.Descriptor instead.
func (*GetParkingLotsByUserIDRequest) Descriptor() ([]byte, []int) {
	return file_parking_proto_rawDescGZIP(), []int{10}
}

func (x *GetParkingLotsByUserIDRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetParkingLotsByUserIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParkingLot    []*ParkingLot          `protobuf:"bytes,1,rep,name=parking_lot,json=parkingLot,proto3" json:"parking_lot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetParkingLotsByUserIDResponse) Reset() {
	*x = GetParkingLotsByUserIDResponse{}
	mi := &file_parking_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetParkingLotsByUserIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetParkingLotsByUserIDResponse) ProtoMessage() {}

func (x *GetParkingLotsByUserIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_parking_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetParkingLotsByUserIDResponse.ProtoReflect.Descriptor instead.
func (*GetParkingLotsByUserIDResponse) Descriptor() ([]byte, []int) {
	return file_parking_proto_rawDescGZIP(), []int{11}
}

func (x *GetParkingLotsByUserIDResponse) GetParkingLot() []*ParkingLot {
	if x != nil {
		return x.ParkingLot
	}
	return nil
}

type ListParkingLotsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListParkingLotsRequest) Reset() {
	*x = ListParkingLotsRequest{}
	mi := &file_parking_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListParkingLotsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListParkingLotsRequest) ProtoMessage() {}

func (x *ListParkingLotsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_parking_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListParkingLotsRequest.ProtoReflect.Descriptor instead.
func (*ListParkingLotsRequest) Descriptor() ([]byte, []int) {
	return file_parking_proto_rawDescGZIP(), []int{12}
}

type ListParkingLotsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParkingLot    []*ParkingLot          `protobuf:"bytes,1,rep,name=parking_lot,json=parkingLot,proto3" json:"parking_lot,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListParkingLotsResponse) Reset() {
	*x = ListParkingLotsResponse{}
	mi := &file_parking_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListParkingLotsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListParkingLotsResponse) ProtoMessage() {}

func (x *ListParkingLotsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_parking_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListParkingLotsResponse.ProtoReflect.Descriptor instead.
func (*ListParkingLotsResponse) Descriptor() ([]byte, []int) {
	return file_parking_proto_rawDescGZIP(), []int{13}
}

func (x *ListParkingLotsResponse) GetParkingLot() []*ParkingLot {
	if x != nil {
		return x.ParkingLot
	}
	return nil
}

func (x *ListParkingLotsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type ParkingLot struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Number int64                  `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	// Тип парковочного места: для инвалидов, спец. назначения и др.
	Type ParkingType `protobuf:"varint,2,opt,name=type,proto3,enum=api.ParkingType" json:"type,omitempty"`
	// Статус парковочного места (забронировано, доступно)
	Status        ParkingLotStatus `protobuf:"varint,3,opt,name=status,proto3,enum=api.ParkingLotStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParkingLot) Reset() {
	*x = ParkingLot{}
	mi := &file_parking_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParkingLot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParkingLot) ProtoMessage() {}

func (x *ParkingLot) ProtoReflect() protoreflect.Message {
	mi := &file_parking_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParkingLot.ProtoReflect.Descriptor instead.
func (*ParkingLot) Descriptor() ([]byte, []int) {
	return file_parking_proto_rawDescGZIP(), []int{14}
}

func (x *ParkingLot) GetNumber() int64 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *ParkingLot) GetType() ParkingType {
	if x != nil {
		return x.Type
	}
	return ParkingType_UNDEFINED_PARKING_TYPE
}

func (x *ParkingLot) GetStatus() ParkingLotStatus {
	if x != nil {
		return x.Status
	}
	return ParkingLotStatus_UNDEFINED_PARKING_LOT_STATUS
}

type User struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// UUID
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Имя
	Name *string `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	// Фамилия
	Surname *string `protobuf:"bytes,3,opt,name=surname,proto3,oneof" json:"surname,omitempty"`
	// Отчество
	Patronymic  *string `protobuf:"bytes,4,opt,name=patronymic,proto3,oneof" json:"patronymic,omitempty"`
	PhoneNumber string  `protobuf:"bytes,5,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Address     *string `protobuf:"bytes,6,opt,name=address,proto3,oneof" json:"address,omitempty"`
	// Тип пользователя
	UserType      UserType `protobuf:"varint,7,opt,name=user_type,json=userType,proto3,enum=api.UserType" json:"user_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_parking_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_parking_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_parking_proto_rawDescGZIP(), []int{15}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *User) GetSurname() string {
	if x != nil && x.Surname != nil {
		return *x.Surname
	}
	return ""
}

func (x *User) GetPatronymic() string {
	if x != nil && x.Patronymic != nil {
		return *x.Patronymic
	}
	return ""
}

func (x *User) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *User) GetAddress() string {
	if x != nil && x.Address != nil {
		return *x.Address
	}
	return ""
}

func (x *User) GetUserType() UserType {
	if x != nil {
		return x.UserType
	}
	return UserType_UNDEFINED_USER_TYPE
}

type Vehicle struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// UUID
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Гос. номер машины
	Number string `protobuf:"bytes,2,opt,name=number,proto3" json:"number,omitempty"`
	// ID владельца машины
	UserId        string `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vehicle) Reset() {
	*x = Vehicle{}
	mi := &file_parking_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vehicle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vehicle) ProtoMessage() {}

func (x *Vehicle) ProtoReflect() protoreflect.Message {
	mi := &file_parking_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vehicle.ProtoReflect.Descriptor instead.
func (*Vehicle) Descriptor() ([]byte, []int) {
	return file_parking_proto_rawDescGZIP(), []int{16}
}

func (x *Vehicle) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Vehicle) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *Vehicle) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ParkingBooking struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParkingLot    string                 `protobuf:"bytes,1,opt,name=parking_lot,json=parkingLot,proto3" json:"parking_lot,omitempty"`
	PhoneNumber   string                 `protobuf:"bytes,2,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	CarPlate      string                 `protobuf:"bytes,4,opt,name=car_plate,json=carPlate,proto3" json:"car_plate,omitempty"`
	TimeFrom      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=time_from,json=timeFrom,proto3" json:"time_from,omitempty"`
	TimeTo        *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=time_to,json=timeTo,proto3" json:"time_to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParkingBooking) Reset() {
	*x = ParkingBooking{}
	mi := &file_parking_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParkingBooking) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParkingBooking) ProtoMessage() {}

func (x *ParkingBooking) ProtoReflect() protoreflect.Message {
	mi := &file_parking_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParkingBooking.ProtoReflect.Descriptor instead.
func (*ParkingBooking) Descriptor() ([]byte, []int) {
	return file_parking_proto_rawDescGZIP(), []int{17}
}

func (x *ParkingBooking) GetParkingLot() string {
	if x != nil {
		return x.ParkingLot
	}
	return ""
}

func (x *ParkingBooking) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *ParkingBooking) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ParkingBooking) GetCarPlate() string {
	if x != nil {
		return x.CarPlate
	}
	return ""
}

func (x *ParkingBooking) GetTimeFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.TimeFrom
	}
	return nil
}

func (x *ParkingBooking) GetTimeTo() *timestamppb.Timestamp {
	if x != nil {
		return x.TimeTo
	}
	return nil
}

type AddParkingBookingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Booking       *ParkingBooking        `protobuf:"bytes,2,opt,name=booking,proto3" json:"booking,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddParkingBookingRequest) Reset() {
	*x = AddParkingBookingRequest{}
	mi := &file_parking_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddParkingBookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddParkingBookingRequest) ProtoMessage() {}

func (x *AddParkingBookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_parking_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddParkingBookingRequest.ProtoReflect.Descriptor instead.
func (*AddParkingBookingRequest) Descriptor() ([]byte, []int) {
	return file_parking_proto_rawDescGZIP(), []int{18}
}

func (x *AddParkingBookingRequest) GetBooking() *ParkingBooking {
	if x != nil {
		return x.Booking
	}
	return nil
}

type AddParkingBookingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParkingLot    string                 `protobuf:"bytes,1,opt,name=parking_lot,json=parkingLot,proto3" json:"parking_lot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddParkingBookingResponse) Reset() {
	*x = AddParkingBookingResponse{}
	mi := &file_parking_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddParkingBookingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddParkingBookingResponse) ProtoMessage() {}

func (x *AddParkingBookingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_parking_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddParkingBookingResponse.ProtoReflect.Descriptor instead.
func (*AddParkingBookingResponse) Descriptor() ([]byte, []int) {
	return file_parking_proto_rawDescGZIP(), []int{19}
}

func (x *AddParkingBookingResponse) GetParkingLot() string {
	if x != nil {
		return x.ParkingLot
	}
	return ""
}

type GetParkingBookingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParkingLot    string                 `protobuf:"bytes,1,opt,name=parking_lot,json=parkingLot,proto3" json:"parking_lot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetParkingBookingRequest) Reset() {
	*x = GetParkingBookingRequest{}
	mi := &file_parking_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetParkingBookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetParkingBookingRequest) ProtoMessage() {}

func (x *GetParkingBookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_parking_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetParkingBookingRequest.ProtoReflect.Descriptor instead.
func (*GetParkingBookingRequest) Descriptor() ([]byte, []int) {
	return file_parking_proto_rawDescGZIP(), []int{20}
}

func (x *GetParkingBookingRequest) GetParkingLot() string {
	if x != nil {
		return x.ParkingLot
	}
	return ""
}

type GetParkingBookingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Booking       *ParkingBooking        `protobuf:"bytes,1,opt,name=booking,proto3" json:"booking,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetParkingBookingResponse) Reset() {
	*x = GetParkingBookingResponse{}
	mi := &file_parking_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetParkingBookingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetParkingBookingResponse) ProtoMessage() {}

func (x *GetParkingBookingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_parking_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetParkingBookingResponse.ProtoReflect.Descriptor instead.
func (*GetParkingBookingResponse) Descriptor() ([]byte, []int) {
	return file_parking_proto_rawDescGZIP(), []int{21}
}

func (x *GetParkingBookingResponse) GetBooking() *ParkingBooking {
	if x != nil {
		return x.Booking
	}
	return nil
}

type GetParkingBookingsListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filter        string                 `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	Limit         int64                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`   // opt
	Offset        int64                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"` // opt
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetParkingBookingsListRequest) Reset() {
	*x = GetParkingBookingsListRequest{}
	mi := &file_parking_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetParkingBookingsListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetParkingBookingsListRequest) ProtoMessage() {}

func (x *GetParkingBookingsListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_parking_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetParkingBookingsListRequest.ProtoReflect.Descriptor instead.
func (*GetParkingBookingsListRequest) Descriptor() ([]byte, []int) {
	return file_parking_proto_rawDescGZIP(), []int{22}
}

func (x *GetParkingBookingsListRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

func (x *GetParkingBookingsListRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetParkingBookingsListRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetParkingBookingsListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bookings      []*ParkingBooking      `protobuf:"bytes,1,rep,name=bookings,proto3" json:"bookings,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetParkingBookingsListResponse) Reset() {
	*x = GetParkingBookingsListResponse{}
	mi := &file_parking_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetParkingBookingsListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetParkingBookingsListResponse) ProtoMessage() {}

func (x *GetParkingBookingsListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_parking_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetParkingBookingsListResponse.ProtoReflect.Descriptor instead.
func (*GetParkingBookingsListResponse) Descriptor() ([]byte, []int) {
	return file_parking_proto_rawDescGZIP(), []int{23}
}

func (x *GetParkingBookingsListResponse) GetBookings() []*ParkingBooking {
	if x != nil {
		return x.Bookings
	}
	return nil
}

func (x *GetParkingBookingsListResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_parking_proto protoreflect.FileDescriptor

const file_parking_proto_rawDesc = "" +
	"\n" +
	"\rparking.proto\x12\x03api\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"2\n" +
	"\x12GetUserByIDRequest\x12\x1c\n" +
	"\auser_id\x18\x01 \x01(\tB\x03\xe0A\x02R\x06userId\"4\n" +
	"\x13GetUserByIDResponse\x12\x1d\n" +
	"\x04user\x18\x01 \x01(\v2\t.api.UserR\x04user\"P\n" +
	"\x0fRegisterRequest\x12!\n" +
	"\fphone_number\x18\x01 \x01(\tR\vphoneNumber\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"+\n" +
	"\x10RegisterResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"M\n" +
	"\fLoginRequest\x12!\n" +
	"\fphone_number\x18\x01 \x01(\tR\vphoneNumber\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"=\n" +
	"\rLoginResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x16\n" +
	"\x06userID\x18\x02 \x01(\tR\x06userID\")\n" +
	"\x0eIsAdminRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\",\n" +
	"\x0fIsAdminResponse\x12\x19\n" +
	"\bis_admin\x18\x01 \x01(\bR\aisAdmin\".\n" +
	"\x14GetParkingLotRequest\x12\x16\n" +
	"\x06number\x18\x01 \x01(\x03R\x06number\"I\n" +
	"\x15GetParkingLotResponse\x120\n" +
	"\vparking_lot\x18\x01 \x01(\v2\x0f.api.ParkingLotR\n" +
	"parkingLot\"8\n" +
	"\x1dGetParkingLotsByUserIDRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"R\n" +
	"\x1eGetParkingLotsByUserIDResponse\x120\n" +
	"\vparking_lot\x18\x01 \x03(\v2\x0f.api.ParkingLotR\n" +
	"parkingLot\"\x18\n" +
	"\x16ListParkingLotsRequest\"a\n" +
	"\x17ListParkingLotsResponse\x120\n" +
	"\vparking_lot\x18\x01 \x03(\v2\x0f.api.ParkingLotR\n" +
	"parkingLot\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"y\n" +
	"\n" +
	"ParkingLot\x12\x16\n" +
	"\x06number\x18\x01 \x01(\x03R\x06number\x12$\n" +
	"\x04type\x18\x02 \x01(\x0e2\x10.api.ParkingTypeR\x04type\x12-\n" +
	"\x06status\x18\x03 \x01(\x0e2\x15.api.ParkingLotStatusR\x06status\"\x91\x02\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x1d\n" +
	"\asurname\x18\x03 \x01(\tH\x01R\asurname\x88\x01\x01\x12#\n" +
	"\n" +
	"patronymic\x18\x04 \x01(\tH\x02R\n" +
	"patronymic\x88\x01\x01\x12!\n" +
	"\fphone_number\x18\x05 \x01(\tR\vphoneNumber\x12\x1d\n" +
	"\aaddress\x18\x06 \x01(\tH\x03R\aaddress\x88\x01\x01\x12*\n" +
	"\tuser_type\x18\a \x01(\x0e2\r.api.UserTypeR\buserTypeB\a\n" +
	"\x05_nameB\n" +
	"\n" +
	"\b_surnameB\r\n" +
	"\v_patronymicB\n" +
	"\n" +
	"\b_address\"J\n" +
	"\aVehicle\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06number\x18\x02 \x01(\tR\x06number\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\"\x87\x02\n" +
	"\x0eParkingBooking\x12\x1f\n" +
	"\vparking_lot\x18\x01 \x01(\tR\n" +
	"parkingLot\x12&\n" +
	"\fphone_number\x18\x02 \x01(\tB\x03\xe0A\x02R\vphoneNumber\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\tcar_plate\x18\x04 \x01(\tB\x03\xe0A\x02R\bcarPlate\x12<\n" +
	"\ttime_from\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x02R\btimeFrom\x128\n" +
	"\atime_to\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x02R\x06timeTo\"N\n" +
	"\x18AddParkingBookingRequest\x122\n" +
	"\abooking\x18\x02 \x01(\v2\x13.api.ParkingBookingB\x03\xe0A\x02R\abooking\"<\n" +
	"\x19AddParkingBookingResponse\x12\x1f\n" +
	"\vparking_lot\x18\x01 \x01(\tR\n" +
	"parkingLot\";\n" +
	"\x18GetParkingBookingRequest\x12\x1f\n" +
	"\vparking_lot\x18\x01 \x01(\tR\n" +
	"parkingLot\"J\n" +
	"\x19GetParkingBookingResponse\x12-\n" +
	"\abooking\x18\x01 \x01(\v2\x13.api.ParkingBookingR\abooking\"e\n" +
	"\x1dGetParkingBookingsListRequest\x12\x16\n" +
	"\x06filter\x18\x01 \x01(\tR\x06filter\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x03R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x03R\x06offset\"g\n" +
	"\x1eGetParkingBookingsListResponse\x12/\n" +
	"\bbookings\x18\x01 \x03(\v2\x13.api.ParkingBookingR\bbookings\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total*\x9a\x01\n" +
	"\x10ParkingLotStatus\x12 \n" +
	"\x1cUNDEFINED_PARKING_LOT_STATUS\x10\x00\x12 \n" +
	"\x1cAVAILABLE_PARKING_LOT_STATUS\x10\x01\x12\x1d\n" +
	"\x19BOOKED_PARKING_LOT_STATUS\x10\x02\x12#\n" +
	"\x1fBOOKED_BY_ME_PARKING_LOT_STATUS\x10\x03*\x92\x01\n" +
	"\vParkingType\x12\x1a\n" +
	"\x16UNDEFINED_PARKING_TYPE\x10\x00\x12\x1a\n" +
	"\x16PERMANENT_PARKING_TYPE\x10\x01\x12\x15\n" +
	"\x11RENT_PARKING_TYPE\x10\x02\x12\x18\n" +
	"\x14SPECIAL_PARKING_TYPE\x10\x03\x12\x1a\n" +
	"\x16INCLUSIVE_PARKING_TYPE\x10\x04*w\n" +
	"\bUserType\x12\x17\n" +
	"\x13UNDEFINED_USER_TYPE\x10\x00\x12\x15\n" +
	"\x11REGULAR_USER_TYPE\x10\x01\x12\x1e\n" +
	"\x1aMANAGING_COMPANY_USER_TYPE\x10\x02\x12\x1b\n" +
	"\x17ADMINISTRATOR_USER_TYPE\x10\x032\x98\a\n" +
	"\n" +
	"ParkingAPI\x12\\\n" +
	"\rGetParkingLot\x12\x19.api.GetParkingLotRequest\x1a\x1a.api.GetParkingLotResponse\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/parking/get\x12\x82\x01\n" +
	"\x16GetParkingLotsByUserID\x12\".api.GetParkingLotsByUserIDRequest\x1a#.api.GetParkingLotsByUserIDResponse\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/parking/get_by_user_id\x12c\n" +
	"\x0fListParkingLots\x12\x1b.api.ListParkingLotsRequest\x1a\x1c.api.ListParkingLotsResponse\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/parking/list\x12k\n" +
	"\x11AddParkingBooking\x12\x1d.api.AddParkingBookingRequest\x1a\x1e.api.AddParkingBookingResponse\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/booking/add\x12h\n" +
	"\x11GetParkingBooking\x12\x1d.api.GetParkingBookingRequest\x1a\x1e.api.GetParkingBookingResponse\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/booking/get\x12x\n" +
	"\x16GetParkingBookingsList\x12\".api.GetParkingBookingsListRequest\x1a#.api.GetParkingBookingsListResponse\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/booking/list\x12Q\n" +
	"\bRegister\x12\x14.api.RegisterRequest\x1a\x15.api.RegisterResponse\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/sso/register\x12E\n" +
	"\x05Login\x12\x11.api.LoginRequest\x1a\x12.api.LoginResponse\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/sso/login\x12W\n" +
	"\vGetUserByID\x12\x17.api.GetUserByIDRequest\x1a\x18.api.GetUserByIDResponse\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/sso/get/userB%Z#internal/pb/parking_lot;parking_lotb\x06proto3"

var (
	file_parking_proto_rawDescOnce sync.Once
	file_parking_proto_rawDescData []byte
)

func file_parking_proto_rawDescGZIP() []byte {
	file_parking_proto_rawDescOnce.Do(func() {
		file_parking_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_parking_proto_rawDesc), len(file_parking_proto_rawDesc)))
	})
	return file_parking_proto_rawDescData
}

var file_parking_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_parking_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_parking_proto_goTypes = []any{
	(ParkingLotStatus)(0),                  // 0: api.ParkingLotStatus
	(ParkingType)(0),                       // 1: api.ParkingType
	(UserType)(0),                          // 2: api.UserType
	(*GetUserByIDRequest)(nil),             // 3: api.GetUserByIDRequest
	(*GetUserByIDResponse)(nil),            // 4: api.GetUserByIDResponse
	(*RegisterRequest)(nil),                // 5: api.RegisterRequest
	(*RegisterResponse)(nil),               // 6: api.RegisterResponse
	(*LoginRequest)(nil),                   // 7: api.LoginRequest
	(*LoginResponse)(nil),                  // 8: api.LoginResponse
	(*IsAdminRequest)(nil),                 // 9: api.IsAdminRequest
	(*IsAdminResponse)(nil),                // 10: api.IsAdminResponse
	(*GetParkingLotRequest)(nil),           // 11: api.GetParkingLotRequest
	(*GetParkingLotResponse)(nil),          // 12: api.GetParkingLotResponse
	(*GetParkingLotsByUserIDRequest)(nil),  // 13: api.GetParkingLotsByUserIDRequest
	(*GetParkingLotsByUserIDResponse)(nil), // 14: api.GetParkingLotsByUserIDResponse
	(*ListParkingLotsRequest)(nil),         // 15: api.ListParkingLotsRequest
	(*ListParkingLotsResponse)(nil),        // 16: api.ListParkingLotsResponse
	(*ParkingLot)(nil),                     // 17: api.ParkingLot
	(*User)(nil),                           // 18: api.User
	(*Vehicle)(nil),                        // 19: api.Vehicle
	(*ParkingBooking)(nil),                 // 20: api.ParkingBooking
	(*AddParkingBookingRequest)(nil),       // 21: api.AddParkingBookingRequest
	(*AddParkingBookingResponse)(nil),      // 22: api.AddParkingBookingResponse
	(*GetParkingBookingRequest)(nil),       // 23: api.GetParkingBookingRequest
	(*GetParkingBookingResponse)(nil),      // 24: api.GetParkingBookingResponse
	(*GetParkingBookingsListRequest)(nil),  // 25: api.GetParkingBookingsListRequest
	(*GetParkingBookingsListResponse)(nil), // 26: api.GetParkingBookingsListResponse
	(*timestamppb.Timestamp)(nil),          // 27: google.protobuf.Timestamp
}
var file_parking_proto_depIdxs = []int32{
	18, // 0: api.GetUserByIDResponse.user:type_name -> api.User
	17, // 1: api.GetParkingLotResponse.parking_lot:type_name -> api.ParkingLot
	17, // 2: api.GetParkingLotsByUserIDResponse.parking_lot:type_name -> api.ParkingLot
	17, // 3: api.ListParkingLotsResponse.parking_lot:type_name -> api.ParkingLot
	1,  // 4: api.ParkingLot.type:type_name -> api.ParkingType
	0,  // 5: api.ParkingLot.status:type_name -> api.ParkingLotStatus
	2,  // 6: api.User.user_type:type_name -> api.UserType
	27, // 7: api.ParkingBooking.time_from:type_name -> google.protobuf.Timestamp
	27, // 8: api.ParkingBooking.time_to:type_name -> google.protobuf.Timestamp
	20, // 9: api.AddParkingBookingRequest.booking:type_name -> api.ParkingBooking
	20, // 10: api.GetParkingBookingResponse.booking:type_name -> api.ParkingBooking
	20, // 11: api.GetParkingBookingsListResponse.bookings:type_name -> api.ParkingBooking
	11, // 12: api.ParkingAPI.GetParkingLot:input_type -> api.GetParkingLotRequest
	13, // 13: api.ParkingAPI.GetParkingLotsByUserID:input_type -> api.GetParkingLotsByUserIDRequest
	15, // 14: api.ParkingAPI.ListParkingLots:input_type -> api.ListParkingLotsRequest
	21, // 15: api.ParkingAPI.AddParkingBooking:input_type -> api.AddParkingBookingRequest
	23, // 16: api.ParkingAPI.GetParkingBooking:input_type -> api.GetParkingBookingRequest
	25, // 17: api.ParkingAPI.GetParkingBookingsList:input_type -> api.GetParkingBookingsListRequest
	5,  // 18: api.ParkingAPI.Register:input_type -> api.RegisterRequest
	7,  // 19: api.ParkingAPI.Login:input_type -> api.LoginRequest
	3,  // 20: api.ParkingAPI.GetUserByID:input_type -> api.GetUserByIDRequest
	12, // 21: api.ParkingAPI.GetParkingLot:output_type -> api.GetParkingLotResponse
	14, // 22: api.ParkingAPI.GetParkingLotsByUserID:output_type -> api.GetParkingLotsByUserIDResponse
	16, // 23: api.ParkingAPI.ListParkingLots:output_type -> api.ListParkingLotsResponse
	22, // 24: api.ParkingAPI.AddParkingBooking:output_type -> api.AddParkingBookingResponse
	24, // 25: api.ParkingAPI.GetParkingBooking:output_type -> api.GetParkingBookingResponse
	26, // 26: api.ParkingAPI.GetParkingBookingsList:output_type -> api.GetParkingBookingsListResponse
	6,  // 27: api.ParkingAPI.Register:output_type -> api.RegisterResponse
	8,  // 28: api.ParkingAPI.Login:output_type -> api.LoginResponse
	4,  // 29: api.ParkingAPI.GetUserByID:output_type -> api.GetUserByIDResponse
	21, // [21:30] is the sub-list for method output_type
	12, // [12:21] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_parking_proto_init() }
func file_parking_proto_init() {
	if File_parking_proto != nil {
		return
	}
	file_parking_proto_msgTypes[15].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_parking_proto_rawDesc), len(file_parking_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_parking_proto_goTypes,
		DependencyIndexes: file_parking_proto_depIdxs,
		EnumInfos:         file_parking_proto_enumTypes,
		MessageInfos:      file_parking_proto_msgTypes,
	}.Build()
	File_parking_proto = out.File
	file_parking_proto_goTypes = nil
	file_parking_proto_depIdxs = nil
}
